// Auth middleware for every server function (AGENTS.md § Conventions).
//
// NOTE: this file used to carry a "This file is automatically generated. Do not
// edit it directly." header inherited from the project scaffold. It was never
// true — nothing generates this file, and `guard-generated.mjs` does not list
// it — but it did deter edits to the hottest code path in the app.
//
// Per-request client, deliberately: it carries the caller's bearer token, so it
// MUST NOT be hoisted to module scope (that would leak one user's credentials
// into another's request). Hoisting buys nothing anyway — supabase-js keeps its
// JWKS cache in a module-level map keyed by `storageKey`, which it derives from
// the project ref (`sb-<ref>-auth-token`). Every client here is built from the
// same SUPABASE_URL, so they all share one cache entry already.
// Pinned by `auth-middleware.jwks-cache.test.ts`; see docs/performance-audit.md
// finding C-1.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { logger } from "@/shared/lib/logger";
// La VÉRIFICATION vit désormais dans `auth-request.ts` (étude 11 lot 3) : la
// route SSE du tuteur en a besoin elle aussi, et deux vérifications de jeton qui
// divergent, c'est une porte qui finit par s'ouvrir moins fort que l'autre. Ce
// fichier garde ce qui lui appartient — la MISE EN FORME du refus pour une
// server fn (une `Error` dont le message remonte au client) et la mesure de
// lenteur.
import { missingSupabaseEnv, resolveSupabaseAuth } from "./auth-request";

/**
 * Above this, a server function is worth a log line. 1 s is deliberately well
 * clear of a healthy call (a PostgREST round-trip from the same region is tens
 * of ms), so the log stays a signal rather than a stream.
 */
const SLOW_SERVER_FN_MS = 1000;

/** Request path without the query string, which can carry tokens. */
function pathOf(request: { url?: string } | undefined): string {
  try {
    return request?.url ? new URL(request.url).pathname : "unknown";
  } catch {
    return "unknown";
  }
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    // L'environnement d'ABORD, avant même de regarder la requête : une variable
    // manquante est une panne de déploiement, et la nommer ainsi évite au
    // prochain lecteur de chercher un jeton absent qui n'est pas le problème.
    const missing = missingSupabaseEnv();
    if (missing.length > 0) {
      logger.error("Supabase auth middleware misconfiguration", { missing });
      throw new Error(
        `Missing Supabase environment variable(s): ${missing.join(", ")}. Set them in your deployment environment.`,
      );
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const resolved = await resolveSupabaseAuth(request);

    if (!resolved.ok) {
      const meta = { path: pathOf(request), error: resolved.detail ?? resolved.failure };

      if (resolved.failure === "BAD_SCHEME") {
        throw new Error("Unauthorized: Only Bearer tokens are supported");
      }

      if (resolved.failure === "EMPTY_TOKEN") {
        throw new Error("Unauthorized: No token provided");
      }

      if (resolved.failure === "NO_SUBJECT") {
        throw new Error("Unauthorized: No user ID found in token");
      }

      if (resolved.failure === "NO_HEADER") {
        // PAS auto-évident, contrairement à ce que la place de ce refus suggère.
        // Une server fn authentifiée n'est jamais appelée sans en-tête « par
        // accident » : `attachSupabaseAuth` en pose un dès qu'une session existe.
        // Arriver ici signifie donc que le CLIENT n'a pas pu produire de jeton —
        // typiquement un rafraîchissement qui a échoué (voir `auth-attacher.ts`).
        // C'est exactement la panne du 2026-08-18 (« Failed to load dashboard »
        // que seule une reconnexion levait), et elle était INVISIBLE : ce refus-ci
        // précède le bloc de journalisation ajouté par #773, donc rien n'en
        // sortait. Une ligne ici, et la prochaine occurrence se nomme toute seule.
        //
        // Elle s'est nommée : le message ci-dessous est resté treize jours hors
        // du vocabulaire de reprise du client, qui ne connaissait que « Invalid
        // token » — donc rien ne forçait de jeton neuf, et l'écran d'erreur se
        // rejouait à l'identique. Ce refus est reconnu depuis le 2026-08-31
        // (`auth-rejection.ts`) ; le libellé exact fait partie du contrat, il est
        // épinglé des deux côtés par des tests.
        logger.warn("Server fn called without a bearer token", { path: pathOf(request) });
        throw new Error("Unauthorized: No authorization header provided");
      }

      if (resolved.failure === "UNAVAILABLE") {
        // `error` (not `warn`): this is an incident, and only `error` reaches
        // the monitoring sink. Naming it "Unauthorized" would be a lie that
        // sends the next reader hunting for a bad token.
        logger.error("Auth verification unavailable", meta);
        throw new Error("Auth verification unavailable. Please try again.");
      }

      // A rejected token is ROUTINE (every session expires), so it stays a
      // warning — an error line here would drown the incident above in noise.
      logger.warn("Bearer token rejected", meta);
      throw new Error("Unauthorized: Invalid token");
    }

    const { supabase, userId, claims } = resolved;

    // Slow server-fn timing (perf audit M-1, server half). Every server fn runs
    // through this middleware, so it is the one place that can time all ~33
    // without touching each. Only SLOW calls are logged: a line per call would
    // cost more than it tells, and the question being answered is "which server
    // fn is dragging p95", not "what happened".
    const startedAt = Date.now();
    try {
      return await next({
        context: {
          supabase,
          userId,
          claims,
        },
      });
    } finally {
      const durationMs = Date.now() - startedAt;
      if (durationMs >= SLOW_SERVER_FN_MS) {
        // Path only — never the query string, which can carry tokens.
        logger.warn("Slow server function", { path: pathOf(request), durationMs });
      }
    }
  },
);
