// Auth middleware for every server function (AGENTS.md § Conventions).
//
// NOTE: this file used to carry a "This file is automatically generated. Do not
// edit it directly." header inherited from the project scaffold. It was never
// true — nothing generates this file, and `guard-generated.mjs` does not list
// it — but it did deter edits to the hottest code path in the app.
//
// Per-request client, deliberately: it carries the caller's bearer token, so it
// MUST NOT be hoisted to module scope (that would leak one user's credentials
// into another's request). Hoisting buys nothing anyway — supabase-js keeps its
// JWKS cache in a module-level map keyed by `storageKey`, which it derives from
// the project ref (`sb-<ref>-auth-token`). Every client here is built from the
// same SUPABASE_URL, so they all share one cache entry already.
// Pinned by `auth-middleware.jwks-cache.test.ts`; see docs/performance-audit.md
// finding C-1.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { logger } from "@/shared/lib/logger";

/**
 * Above this, a server function is worth a log line. 1 s is deliberately well
 * clear of a healthy call (a PostgREST round-trip from the same region is tens
 * of ms), so the log stays a signal rather than a stream.
 */
const SLOW_SERVER_FN_MS = 1000;

/** Request path without the query string, which can carry tokens. */
function pathOf(request: { url?: string } | undefined): string {
  try {
    return request?.url ? new URL(request.url).pathname : "unknown";
  } catch {
    return "unknown";
  }
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Set them in your deployment environment.`;
      logger.error("Supabase auth middleware misconfiguration", { missing });
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    if (!authHeader.startsWith("Bearer ")) {
      throw new Error("Unauthorized: Only Bearer tokens are supported");
    }

    const token = authHeader.replace("Bearer ", "");
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub) {
      throw new Error("Unauthorized: No user ID found in token");
    }

    // Slow server-fn timing (perf audit M-1, server half). Every server fn runs
    // through this middleware, so it is the one place that can time all ~33
    // without touching each. Only SLOW calls are logged: a line per call would
    // cost more than it tells, and the question being answered is "which server
    // fn is dragging p95", not "what happened".
    const startedAt = Date.now();
    try {
      return await next({
        context: {
          supabase,
          userId: data.claims.sub,
          claims: data.claims,
        },
      });
    } finally {
      const durationMs = Date.now() - startedAt;
      if (durationMs >= SLOW_SERVER_FN_MS) {
        // Path only — never the query string, which can carry tokens.
        logger.warn("Slow server function", { path: pathOf(request), durationMs });
      }
    }
  },
);
