/**
 * Compiles the harness sources into the per-tool views they feed (étude 25 D-4).
 *
 *   sources                          →  generated view
 *   ------------------------------------------------------------------
 *   harness/policy.json              →  .claude/settings.json (permissions)
 *   harness/models.json              →  .claude/settings.json (hook model)
 *   harness/prompts/*.md             →  .claude/settings.json (hook prompt)
 *
 * Same philosophy as the content pipeline: edit the SOURCE, run the build, never
 * hand-edit the output. `guard-generated.mjs` blocks the edit locally and
 * `npm run harness:check` fails CI if a committed view drifts from its sources.
 *
 * The output must be byte-identical to what Prettier would produce (2-space
 * indent + trailing newline), otherwise lint-staged reformats the generated file
 * on commit and the drift check fails on the next run. Same reason the prompt
 * markdown is read verbatim: it is Prettier-normalised at rest.
 *
 * Pure builders are exported (and unit-tested); `main()` does the I/O and runs
 * only when this file is executed directly.
 *
 *   node scripts/harness/sync.mjs            # write the views
 *   node scripts/harness/sync.mjs --check    # report drift, write nothing
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { pathToFileURL } from "node:url";

const ROOT = join(import.meta.dirname, "..", "..");

const DO_NOT_EDIT =
  "GENERATED by `npm run harness:sync` from harness/policy.json + harness/models.json + " +
  "harness/prompts/. DO NOT EDIT BY HAND — edit the source and re-run the sync (étude 25 D-4).";

/** Flattens the intent-grouped allow map into the flat list Claude Code expects. */
export function flattenAllow(allow) {
  return Object.entries(allow ?? {})
    .filter(([key]) => !key.startsWith("$"))
    .flatMap(([, rules]) => (Array.isArray(rules) ? rules : []));
}

/** Builds the full .claude/settings.json object from the harness sources. */
export function buildClaudeSettings({ policy, models, preCommitPrompt }) {
  const hookModel = models?.roles?.["hook-precommit"]?.model;
  if (!hookModel) {
    throw new Error(
      "harness/models.json: role 'hook-precommit' has no model — cannot build the pre-commit hook.",
    );
  }

  return {
    $schema: "https://json.schemastore.org/claude-code-settings.json",
    $comment: DO_NOT_EDIT,
    permissions: {
      allow: flattenAllow(policy.allow),
      deny: (policy.deny ?? []).map((entry) => entry.rule),
    },
    hooks: {
      PreToolUse: [
        {
          matcher: "Edit|Write|MultiEdit",
          hooks: [{ type: "command", command: "node .claude/hooks/guard-generated.mjs" }],
        },
        {
          matcher: "Bash",
          hooks: [
            {
              type: "agent",
              if: "Bash(git commit*)",
              model: hookModel,
              timeout: 180,
              statusMessage: "Garde pré-commit (checks bloquants)…",
              prompt: preCommitPrompt,
            },
          ],
        },
      ],
      PostToolUse: [
        {
          matcher: "Edit|Write|MultiEdit",
          hooks: [{ type: "command", command: "node .claude/hooks/format-changed.mjs" }],
        },
      ],
    },
  };
}

/** Prettier-compatible JSON serialisation (2-space indent, trailing newline). */
export function serialise(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

/** Reads the harness sources from disk. Exported so the gate reuses the exact same inputs. */
export function readSources(root = ROOT) {
  return {
    policy: JSON.parse(readFileSync(join(root, "harness", "policy.json"), "utf8")),
    models: JSON.parse(readFileSync(join(root, "harness", "models.json"), "utf8")),
    preCommitPrompt: readFileSync(
      join(root, "harness", "prompts", "pre-commit-guard.md"),
      "utf8",
    ).trim(),
  };
}

/**
 * Mirrors `.claude/skills/**` into `.agents/skills/**` — the neutral path that
 * Codex, Gemini CLI, Cursor, Copilot and Amp all discover (étude 25 D-2). The
 * files are copied verbatim: SKILL.md is an open standard (agentskills.io), so
 * no translation is needed, only a second location.
 *
 * No exclusion manifest: since the étude 24 split, the only skills left in this
 * repo are the technical ones (verify, code-review and the guards) and all of
 * them are meant to be portable. An empty "just in case" config would be dead
 * weight — add one the day a skill must stay Claude-only.
 */
export function buildSkillMirror(root = ROOT) {
  const source = join(root, ".claude", "skills");
  if (!existsSync(source)) return [];

  const views = [];
  for (const skill of readdirSync(source, { withFileTypes: true })) {
    if (!skill.isDirectory()) continue;
    for (const file of walkFiles(join(source, skill.name))) {
      const relative = file
        .slice(join(source, skill.name).length + 1)
        .split("\\")
        .join("/");
      views.push([`.agents/skills/${skill.name}/${relative}`, readFileSync(file, "utf8")]);
    }
  }
  return views;
}

/** Every file under `dir`, recursively. */
function walkFiles(dir) {
  const out = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...walkFiles(full));
    else out.push(full);
  }
  return out;
}

/** The full list of generated views: [relative path, expected content]. */
export function buildViews(root = ROOT) {
  const sources = readSources(root);
  return [
    [".claude/settings.json", serialise(buildClaudeSettings(sources))],
    ...buildSkillMirror(root),
  ];
}

function main() {
  const checkOnly = process.argv.includes("--check");
  const drifted = [];

  for (const [relPath, expected] of buildViews()) {
    const absPath = join(ROOT, relPath);
    let actual = null;
    try {
      actual = readFileSync(absPath, "utf8");
    } catch {
      actual = null;
    }

    if (actual === expected) {
      console.log(`[harness:sync] ${relPath} — up to date.`);
      continue;
    }

    if (checkOnly) {
      drifted.push(relPath);
      continue;
    }

    mkdirSync(dirname(absPath), { recursive: true });
    writeFileSync(absPath, expected);
    console.log(`[harness:sync] ${relPath} — ${actual === null ? "created" : "updated"}.`);
  }

  if (drifted.length > 0) {
    for (const relPath of drifted) {
      console.error(
        `::error file=${relPath}::${relPath} is out of sync with its harness sources — run \`npm run harness:sync\` and commit the result.`,
      );
    }
    throw new Error(`${drifted.length} generated view(s) drifted from harness/.`);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    main();
  } catch (err) {
    console.error(`\n✗ ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  }
}
