/**
 * Compiles the harness sources into the per-tool views they feed (étude 25 D-4).
 *
 *   sources                          →  generated view
 *   ------------------------------------------------------------------
 *   harness/policy.json              →  .claude/settings.json (permissions)
 *   harness/models.json              →  .claude/settings.json (hook model)
 *   harness/prompts/*.md             →  .claude/settings.json (hook prompt)
 *
 * Same philosophy as the content pipeline: edit the SOURCE, run the build, never
 * hand-edit the output. `guard-generated.mjs` blocks the edit locally and
 * `npm run harness:check` fails CI if a committed view drifts from its sources.
 *
 * The output must be byte-identical to what Prettier would produce (2-space
 * indent + trailing newline), otherwise lint-staged reformats the generated file
 * on commit and the drift check fails on the next run. Same reason the prompt
 * markdown is read verbatim: it is Prettier-normalised at rest.
 *
 * Pure builders are exported (and unit-tested); `main()` does the I/O and runs
 * only when this file is executed directly.
 *
 *   node scripts/harness/sync.mjs            # write the views
 *   node scripts/harness/sync.mjs --check    # report drift, write nothing
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

const ROOT = join(import.meta.dirname, "..", "..");

const DO_NOT_EDIT =
  "GENERATED by `npm run harness:sync` from harness/policy.json + harness/models.json + " +
  "harness/prompts/. DO NOT EDIT BY HAND — edit the source and re-run the sync (étude 25 D-4).";

/** Flattens the intent-grouped allow map into the flat list Claude Code expects. */
export function flattenAllow(allow) {
  return Object.entries(allow ?? {})
    .filter(([key]) => !key.startsWith("$"))
    .flatMap(([, rules]) => (Array.isArray(rules) ? rules : []));
}

/** Builds the full .claude/settings.json object from the harness sources. */
export function buildClaudeSettings({ policy, models, preCommitPrompt }) {
  const hookModel = models?.roles?.["hook-precommit"]?.model;
  if (!hookModel) {
    throw new Error(
      "harness/models.json: role 'hook-precommit' has no model — cannot build the pre-commit hook.",
    );
  }

  return {
    $schema: "https://json.schemastore.org/claude-code-settings.json",
    $comment: DO_NOT_EDIT,
    permissions: {
      allow: flattenAllow(policy.allow),
      deny: (policy.deny ?? []).map((entry) => entry.rule),
    },
    hooks: {
      PreToolUse: [
        {
          matcher: "Edit|Write|MultiEdit",
          hooks: [{ type: "command", command: "node .claude/hooks/guard-generated.mjs" }],
        },
        {
          matcher: "Bash",
          hooks: [
            {
              type: "agent",
              if: "Bash(git commit*)",
              model: hookModel,
              timeout: 180,
              statusMessage: "Garde pré-commit (checks bloquants)…",
              prompt: preCommitPrompt,
            },
          ],
        },
      ],
      PostToolUse: [
        {
          matcher: "Edit|Write|MultiEdit",
          hooks: [{ type: "command", command: "node .claude/hooks/format-changed.mjs" }],
        },
      ],
    },
  };
}

/** Prettier-compatible JSON serialisation (2-space indent, trailing newline). */
export function serialise(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

/** Reads the harness sources from disk. Exported so the gate reuses the exact same inputs. */
export function readSources(root = ROOT) {
  return {
    policy: JSON.parse(readFileSync(join(root, "harness", "policy.json"), "utf8")),
    models: JSON.parse(readFileSync(join(root, "harness", "models.json"), "utf8")),
    preCommitPrompt: readFileSync(
      join(root, "harness", "prompts", "pre-commit-guard.md"),
      "utf8",
    ).trim(),
  };
}

/** The full list of generated views: [relative path, expected content]. */
export function buildViews(root = ROOT) {
  const sources = readSources(root);
  return [[".claude/settings.json", serialise(buildClaudeSettings(sources))]];
}

function main() {
  const checkOnly = process.argv.includes("--check");
  const drifted = [];

  for (const [relPath, expected] of buildViews()) {
    const absPath = join(ROOT, relPath);
    let actual = null;
    try {
      actual = readFileSync(absPath, "utf8");
    } catch {
      actual = null;
    }

    if (actual === expected) {
      console.log(`[harness:sync] ${relPath} — up to date.`);
      continue;
    }

    if (checkOnly) {
      drifted.push(relPath);
      continue;
    }

    writeFileSync(absPath, expected);
    console.log(`[harness:sync] ${relPath} — ${actual === null ? "created" : "updated"}.`);
  }

  if (drifted.length > 0) {
    for (const relPath of drifted) {
      console.error(
        `::error file=${relPath}::${relPath} is out of sync with its harness sources — run \`npm run harness:sync\` and commit the result.`,
      );
    }
    throw new Error(`${drifted.length} generated view(s) drifted from harness/.`);
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    main();
  } catch (err) {
    console.error(`\n✗ ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  }
}
