/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicProgrammeRouteImport } from './routes/_public/programme'
import { Route as PublicExtrasRouteImport } from './routes/_public/extras'
import { Route as AuthenticatedThemesRouteImport } from './routes/_authenticated/themes'
import { Route as AuthenticatedParentReportRouteImport } from './routes/_authenticated/parent-report'
import { Route as AuthenticatedParcoursRouteImport } from './routes/_authenticated/parcours'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedDungeonRouteImport } from './routes/_authenticated/dungeon'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as PublicNiveauParcoursIdRouteImport } from './routes/_public/niveau.$parcoursId'
import { Route as PublicMatiereSubjectIdRouteImport } from './routes/_public/matiere.$subjectId'
import { Route as PublicExerciceExerciseIdRouteImport } from './routes/_public/exercice.$exerciseId'
import { Route as PublicChapitreChapterIdRouteImport } from './routes/_public/chapitre.$chapterId'
import { Route as AuthenticatedThemesFamilyIdRouteImport } from './routes/_authenticated/themes_.$familyId'
import { Route as AuthenticatedSubjectSubjectIdRouteImport } from './routes/_authenticated/subject.$subjectId'
import { Route as AuthenticatedQuestExerciseIdRouteImport } from './routes/_authenticated/quest.$exerciseId'
import { Route as AuthenticatedLessonChapterIdRouteImport } from './routes/_authenticated/lesson.$chapterId'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedAdminParcoursInterestRouteImport } from './routes/_authenticated/admin.parcours-interest'
import { Route as AuthenticatedAdminContentReportsRouteImport } from './routes/_authenticated/admin.content-reports'
import { Route as AuthenticatedAdminBetaRequestsRouteImport } from './routes/_authenticated/admin.beta-requests'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicProgrammeRoute = PublicProgrammeRouteImport.update({
  id: '/programme',
  path: '/programme',
  getParentRoute: () => PublicRoute,
} as any)
const PublicExtrasRoute = PublicExtrasRouteImport.update({
  id: '/extras',
  path: '/extras',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedThemesRoute = AuthenticatedThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentReportRoute =
  AuthenticatedParentReportRouteImport.update({
    id: '/parent-report',
    path: '/parent-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedParcoursRoute = AuthenticatedParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDungeonRoute = AuthenticatedDungeonRouteImport.update({
  id: '/dungeon',
  path: '/dungeon',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PublicNiveauParcoursIdRoute = PublicNiveauParcoursIdRouteImport.update({
  id: '/niveau/$parcoursId',
  path: '/niveau/$parcoursId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMatiereSubjectIdRoute = PublicMatiereSubjectIdRouteImport.update({
  id: '/matiere/$subjectId',
  path: '/matiere/$subjectId',
  getParentRoute: () => PublicRoute,
} as any)
const PublicExerciceExerciseIdRoute =
  PublicExerciceExerciseIdRouteImport.update({
    id: '/exercice/$exerciseId',
    path: '/exercice/$exerciseId',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicChapitreChapterIdRoute = PublicChapitreChapterIdRouteImport.update({
  id: '/chapitre/$chapterId',
  path: '/chapitre/$chapterId',
  getParentRoute: () => PublicRoute,
} as any)
const AuthenticatedThemesFamilyIdRoute =
  AuthenticatedThemesFamilyIdRouteImport.update({
    id: '/themes_/$familyId',
    path: '/themes/$familyId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubjectSubjectIdRoute =
  AuthenticatedSubjectSubjectIdRouteImport.update({
    id: '/subject/$subjectId',
    path: '/subject/$subjectId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuestExerciseIdRoute =
  AuthenticatedQuestExerciseIdRouteImport.update({
    id: '/quest/$exerciseId',
    path: '/quest/$exerciseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLessonChapterIdRoute =
  AuthenticatedLessonChapterIdRouteImport.update({
    id: '/lesson/$chapterId',
    path: '/lesson/$chapterId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/admin/subscriptions',
    path: '/admin/subscriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminParcoursInterestRoute =
  AuthenticatedAdminParcoursInterestRouteImport.update({
    id: '/admin/parcours-interest',
    path: '/admin/parcours-interest',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminContentReportsRoute =
  AuthenticatedAdminContentReportsRouteImport.update({
    id: '/admin/content-reports',
    path: '/admin/content-reports',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBetaRequestsRoute =
  AuthenticatedAdminBetaRequestsRouteImport.update({
    id: '/admin/beta-requests',
    path: '/admin/beta-requests',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dungeon': typeof AuthenticatedDungeonRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/parcours': typeof AuthenticatedParcoursRoute
  '/parent-report': typeof AuthenticatedParentReportRoute
  '/themes': typeof AuthenticatedThemesRoute
  '/extras': typeof PublicExtrasRoute
  '/programme': typeof PublicProgrammeRoute
  '/admin/beta-requests': typeof AuthenticatedAdminBetaRequestsRoute
  '/admin/content-reports': typeof AuthenticatedAdminContentReportsRoute
  '/admin/parcours-interest': typeof AuthenticatedAdminParcoursInterestRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/lesson/$chapterId': typeof AuthenticatedLessonChapterIdRoute
  '/quest/$exerciseId': typeof AuthenticatedQuestExerciseIdRoute
  '/subject/$subjectId': typeof AuthenticatedSubjectSubjectIdRoute
  '/themes/$familyId': typeof AuthenticatedThemesFamilyIdRoute
  '/chapitre/$chapterId': typeof PublicChapitreChapterIdRoute
  '/exercice/$exerciseId': typeof PublicExerciceExerciseIdRoute
  '/matiere/$subjectId': typeof PublicMatiereSubjectIdRoute
  '/niveau/$parcoursId': typeof PublicNiveauParcoursIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dungeon': typeof AuthenticatedDungeonRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/parcours': typeof AuthenticatedParcoursRoute
  '/parent-report': typeof AuthenticatedParentReportRoute
  '/themes': typeof AuthenticatedThemesRoute
  '/extras': typeof PublicExtrasRoute
  '/programme': typeof PublicProgrammeRoute
  '/admin/beta-requests': typeof AuthenticatedAdminBetaRequestsRoute
  '/admin/content-reports': typeof AuthenticatedAdminContentReportsRoute
  '/admin/parcours-interest': typeof AuthenticatedAdminParcoursInterestRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/lesson/$chapterId': typeof AuthenticatedLessonChapterIdRoute
  '/quest/$exerciseId': typeof AuthenticatedQuestExerciseIdRoute
  '/subject/$subjectId': typeof AuthenticatedSubjectSubjectIdRoute
  '/themes/$familyId': typeof AuthenticatedThemesFamilyIdRoute
  '/chapitre/$chapterId': typeof PublicChapitreChapterIdRoute
  '/exercice/$exerciseId': typeof PublicExerciceExerciseIdRoute
  '/matiere/$subjectId': typeof PublicMatiereSubjectIdRoute
  '/niveau/$parcoursId': typeof PublicNiveauParcoursIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dungeon': typeof AuthenticatedDungeonRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/parcours': typeof AuthenticatedParcoursRoute
  '/_authenticated/parent-report': typeof AuthenticatedParentReportRoute
  '/_authenticated/themes': typeof AuthenticatedThemesRoute
  '/_public/extras': typeof PublicExtrasRoute
  '/_public/programme': typeof PublicProgrammeRoute
  '/_authenticated/admin/beta-requests': typeof AuthenticatedAdminBetaRequestsRoute
  '/_authenticated/admin/content-reports': typeof AuthenticatedAdminContentReportsRoute
  '/_authenticated/admin/parcours-interest': typeof AuthenticatedAdminParcoursInterestRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/lesson/$chapterId': typeof AuthenticatedLessonChapterIdRoute
  '/_authenticated/quest/$exerciseId': typeof AuthenticatedQuestExerciseIdRoute
  '/_authenticated/subject/$subjectId': typeof AuthenticatedSubjectSubjectIdRoute
  '/_authenticated/themes_/$familyId': typeof AuthenticatedThemesFamilyIdRoute
  '/_public/chapitre/$chapterId': typeof PublicChapitreChapterIdRoute
  '/_public/exercice/$exerciseId': typeof PublicExerciceExerciseIdRoute
  '/_public/matiere/$subjectId': typeof PublicMatiereSubjectIdRoute
  '/_public/niveau/$parcoursId': typeof PublicNiveauParcoursIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/dungeon'
    | '/leaderboard'
    | '/onboarding'
    | '/parcours'
    | '/parent-report'
    | '/themes'
    | '/extras'
    | '/programme'
    | '/admin/beta-requests'
    | '/admin/content-reports'
    | '/admin/parcours-interest'
    | '/admin/subscriptions'
    | '/lesson/$chapterId'
    | '/quest/$exerciseId'
    | '/subject/$subjectId'
    | '/themes/$familyId'
    | '/chapitre/$chapterId'
    | '/exercice/$exerciseId'
    | '/matiere/$subjectId'
    | '/niveau/$parcoursId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/dungeon'
    | '/leaderboard'
    | '/onboarding'
    | '/parcours'
    | '/parent-report'
    | '/themes'
    | '/extras'
    | '/programme'
    | '/admin/beta-requests'
    | '/admin/content-reports'
    | '/admin/parcours-interest'
    | '/admin/subscriptions'
    | '/lesson/$chapterId'
    | '/quest/$exerciseId'
    | '/subject/$subjectId'
    | '/themes/$familyId'
    | '/chapitre/$chapterId'
    | '/exercice/$exerciseId'
    | '/matiere/$subjectId'
    | '/niveau/$parcoursId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_public'
    | '/auth'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/dungeon'
    | '/_authenticated/leaderboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/parcours'
    | '/_authenticated/parent-report'
    | '/_authenticated/themes'
    | '/_public/extras'
    | '/_public/programme'
    | '/_authenticated/admin/beta-requests'
    | '/_authenticated/admin/content-reports'
    | '/_authenticated/admin/parcours-interest'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/lesson/$chapterId'
    | '/_authenticated/quest/$exerciseId'
    | '/_authenticated/subject/$subjectId'
    | '/_authenticated/themes_/$familyId'
    | '/_public/chapitre/$chapterId'
    | '/_public/exercice/$exerciseId'
    | '/_public/matiere/$subjectId'
    | '/_public/niveau/$parcoursId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/programme': {
      id: '/_public/programme'
      path: '/programme'
      fullPath: '/programme'
      preLoaderRoute: typeof PublicProgrammeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/extras': {
      id: '/_public/extras'
      path: '/extras'
      fullPath: '/extras'
      preLoaderRoute: typeof PublicExtrasRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/themes': {
      id: '/_authenticated/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof AuthenticatedThemesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent-report': {
      id: '/_authenticated/parent-report'
      path: '/parent-report'
      fullPath: '/parent-report'
      preLoaderRoute: typeof AuthenticatedParentReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parcours': {
      id: '/_authenticated/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof AuthenticatedParcoursRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dungeon': {
      id: '/_authenticated/dungeon'
      path: '/dungeon'
      fullPath: '/dungeon'
      preLoaderRoute: typeof AuthenticatedDungeonRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_public/niveau/$parcoursId': {
      id: '/_public/niveau/$parcoursId'
      path: '/niveau/$parcoursId'
      fullPath: '/niveau/$parcoursId'
      preLoaderRoute: typeof PublicNiveauParcoursIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/matiere/$subjectId': {
      id: '/_public/matiere/$subjectId'
      path: '/matiere/$subjectId'
      fullPath: '/matiere/$subjectId'
      preLoaderRoute: typeof PublicMatiereSubjectIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/exercice/$exerciseId': {
      id: '/_public/exercice/$exerciseId'
      path: '/exercice/$exerciseId'
      fullPath: '/exercice/$exerciseId'
      preLoaderRoute: typeof PublicExerciceExerciseIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/chapitre/$chapterId': {
      id: '/_public/chapitre/$chapterId'
      path: '/chapitre/$chapterId'
      fullPath: '/chapitre/$chapterId'
      preLoaderRoute: typeof PublicChapitreChapterIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authenticated/themes_/$familyId': {
      id: '/_authenticated/themes_/$familyId'
      path: '/themes/$familyId'
      fullPath: '/themes/$familyId'
      preLoaderRoute: typeof AuthenticatedThemesFamilyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subject/$subjectId': {
      id: '/_authenticated/subject/$subjectId'
      path: '/subject/$subjectId'
      fullPath: '/subject/$subjectId'
      preLoaderRoute: typeof AuthenticatedSubjectSubjectIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quest/$exerciseId': {
      id: '/_authenticated/quest/$exerciseId'
      path: '/quest/$exerciseId'
      fullPath: '/quest/$exerciseId'
      preLoaderRoute: typeof AuthenticatedQuestExerciseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lesson/$chapterId': {
      id: '/_authenticated/lesson/$chapterId'
      path: '/lesson/$chapterId'
      fullPath: '/lesson/$chapterId'
      preLoaderRoute: typeof AuthenticatedLessonChapterIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/parcours-interest': {
      id: '/_authenticated/admin/parcours-interest'
      path: '/admin/parcours-interest'
      fullPath: '/admin/parcours-interest'
      preLoaderRoute: typeof AuthenticatedAdminParcoursInterestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/content-reports': {
      id: '/_authenticated/admin/content-reports'
      path: '/admin/content-reports'
      fullPath: '/admin/content-reports'
      preLoaderRoute: typeof AuthenticatedAdminContentReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/beta-requests': {
      id: '/_authenticated/admin/beta-requests'
      path: '/admin/beta-requests'
      fullPath: '/admin/beta-requests'
      preLoaderRoute: typeof AuthenticatedAdminBetaRequestsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDungeonRoute: typeof AuthenticatedDungeonRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedParcoursRoute: typeof AuthenticatedParcoursRoute
  AuthenticatedParentReportRoute: typeof AuthenticatedParentReportRoute
  AuthenticatedThemesRoute: typeof AuthenticatedThemesRoute
  AuthenticatedAdminBetaRequestsRoute: typeof AuthenticatedAdminBetaRequestsRoute
  AuthenticatedAdminContentReportsRoute: typeof AuthenticatedAdminContentReportsRoute
  AuthenticatedAdminParcoursInterestRoute: typeof AuthenticatedAdminParcoursInterestRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedLessonChapterIdRoute: typeof AuthenticatedLessonChapterIdRoute
  AuthenticatedQuestExerciseIdRoute: typeof AuthenticatedQuestExerciseIdRoute
  AuthenticatedSubjectSubjectIdRoute: typeof AuthenticatedSubjectSubjectIdRoute
  AuthenticatedThemesFamilyIdRoute: typeof AuthenticatedThemesFamilyIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDungeonRoute: AuthenticatedDungeonRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedParcoursRoute: AuthenticatedParcoursRoute,
  AuthenticatedParentReportRoute: AuthenticatedParentReportRoute,
  AuthenticatedThemesRoute: AuthenticatedThemesRoute,
  AuthenticatedAdminBetaRequestsRoute: AuthenticatedAdminBetaRequestsRoute,
  AuthenticatedAdminContentReportsRoute: AuthenticatedAdminContentReportsRoute,
  AuthenticatedAdminParcoursInterestRoute:
    AuthenticatedAdminParcoursInterestRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedLessonChapterIdRoute: AuthenticatedLessonChapterIdRoute,
  AuthenticatedQuestExerciseIdRoute: AuthenticatedQuestExerciseIdRoute,
  AuthenticatedSubjectSubjectIdRoute: AuthenticatedSubjectSubjectIdRoute,
  AuthenticatedThemesFamilyIdRoute: AuthenticatedThemesFamilyIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PublicRouteChildren {
  PublicExtrasRoute: typeof PublicExtrasRoute
  PublicProgrammeRoute: typeof PublicProgrammeRoute
  PublicChapitreChapterIdRoute: typeof PublicChapitreChapterIdRoute
  PublicExerciceExerciseIdRoute: typeof PublicExerciceExerciseIdRoute
  PublicMatiereSubjectIdRoute: typeof PublicMatiereSubjectIdRoute
  PublicNiveauParcoursIdRoute: typeof PublicNiveauParcoursIdRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicExtrasRoute: PublicExtrasRoute,
  PublicProgrammeRoute: PublicProgrammeRoute,
  PublicChapitreChapterIdRoute: PublicChapitreChapterIdRoute,
  PublicExerciceExerciseIdRoute: PublicExerciceExerciseIdRoute,
  PublicMatiereSubjectIdRoute: PublicMatiereSubjectIdRoute,
  PublicNiveauParcoursIdRoute: PublicNiveauParcoursIdRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
