-- Content quality pass — delta (idempotent) for already-migrated databases.
-- Re-upserts only the question rows changed in the quality pass
-- (deepened explanations + correctness fixes). Deterministic ids; safe to
-- re-run. Multi-line prompts handled correctly.

-- Garde de reconstruction sur base VIERGE (ajoutee le 2026-07-20, suite a l'etude 24 lot 4).
--
-- Cette migration est, de son propre aveu, un DELTA pour bases deja migrees : elle re-upsert
-- des questions dont les exercices parents etaient crees par les migrations de contenu
-- GENEREES. Depuis que celles-ci ont quitte le repo public (#544), une base reconstruite a
-- partir du seul repo public n'a plus ces exercices, et l'insert violait
-- questions_exercise_id_fkey : plus aucune base fraiche ne pouvait etre bati, ce qui tuait la
-- suite pgTAP et tout provisionnement d'un projet TEST neuf. La prod, elle, n'a jamais ete
-- affectee (la migration y est appliquee de longue date, et ses exercices existent).
--
-- Le correctif ne retire aucune donnee : chaque ligne n'est inseree QUE si son exercice
-- parent existe. Sur la prod les 41 exercices sont la, le comportement est donc identique ;
-- sur une base fraiche la migration ne fait simplement rien -- ce qui est exactement le sens
-- d'un delta : il n'y a rien a corriger la ou rien n'a encore ete pose.
INSERT INTO public.questions (id, exercise_id, prompt, options, correct_option, explanation, display_order)
SELECT v.id::uuid, v.exercise_id::uuid, v.prompt, v.options::jsonb, v.correct_option,
       v.explanation, v.display_order::int
FROM (VALUES
  ('1bc63cf6-4649-5021-927c-19dbd169687b', '5680c5e9-d223-542e-9db3-4c3e770da622', 'ما قيمة √64 ؟', '[{"id":"a","text":"8"},{"id":"b","text":"6"},{"id":"c","text":"32"},{"id":"d","text":"16"}]'::jsonb, 'a', 'الجذر التربيعي لعدد موجب a هو العدد الموجب الذي مربّعه يساوي a. نبحث عن العدد الذي مربّعه 64: بما أنّ 8² = 8 × 8 = 64 فإنّ √64 = 8. تحقّق: 8² = 64 ✓ (وليس 6 لأنّ 6²=36، ولا 32 أو 16 لأنّ مربّعهما أكبر بكثير).', 1),
  ('d73efe27-cd2b-5ade-b536-f505689746d4', '5680c5e9-d223-542e-9db3-4c3e770da622', 'ما هو الشكل المبسّط للعدد √50 ؟', '[{"id":"a","text":"5√2"},{"id":"b","text":"2√5"},{"id":"c","text":"25√2"},{"id":"d","text":"10√5"}]'::jsonb, 'a', 'لتبسيط الجذر نُخرج أكبر مربّع كامل عاملًا للعدد: 50 = 25 × 2 حيث 25 مربّع كامل. نطبّق خاصيّة جذر الجداء √(a×b) = √a × √b: √50 = √(25 × 2) = √25 × √2 = 5√2. الخيار (b) حلّل 50 خطأً، و(c) لم يُخرج الجذر من 25.', 3),
  ('0e1a8e5a-8a8b-5f8d-abb9-846f550be28f', '5680c5e9-d223-542e-9db3-4c3e770da622', 'ما ناتج √3 × √12 ؟', '[{"id":"a","text":"6"},{"id":"b","text":"√15"},{"id":"c","text":"36"},{"id":"d","text":"√36"}]'::jsonb, 'a', 'نطبّق خاصيّة جذر الجداء √a × √b = √(a×b): √3 × √12 = √(3 × 12) = √36. وبما أنّ 6² = 36 فإنّ √36 = 6. تحقّق: الناتج عدد ناطق لأنّ 3 × 12 = 36 مربّع كامل.', 4),
  ('d4fcdcbc-54d2-512f-a801-a980e162361a', '2d3109e8-a00c-5619-8905-d768c68c00b9', 'بعد إنطاق المقام، يصبح الكسر 1/√2 مساويًا لـ:', '[{"id":"a","text":"√2/2"},{"id":"b","text":"2/√2"},{"id":"c","text":"√2"},{"id":"d","text":"1/2"}]'::jsonb, 'a', 'لإنطاق المقام نتخلّص من الجذر بضرب البسط والمقام في الجذر نفسه √2: (1×√2)/(√2×√2) = √2/(√2)² = √2/2، لأنّ (√2)² = 2. النتيجة 1/√2 = √2/2 وقيمتها لم تتغيّر (نفس العدد ≈ 0.707).', 2),
  ('761705b3-5632-50c3-8e89-1fcbb1a293ee', '2d3109e8-a00c-5619-8905-d768c68c00b9', 'ما هو الشكل المبسّط للعدد √75 ؟', '[{"id":"a","text":"5√3"},{"id":"b","text":"3√5"},{"id":"c","text":"25√3"},{"id":"d","text":"15"}]'::jsonb, 'a', 'نُخرج أكبر مربّع كامل عاملًا للعدد 75: 75 = 25 × 3 حيث 25 مربّع كامل. إذن √75 = √(25 × 3) = √25 × √3 = 5√3. الخيار (b) حلّل العدد خطأً، و(c) لم يُخرج الجذر من 25.', 3),
  ('074173e5-a5fb-57e5-a01d-d884a549b9fb', '93b0884f-f1fa-5677-ba0c-45682a394f86', 'زاويتان متكاملتان (مجموعهما 180°)، وإحداهما تساوي ثلاثة أمثال الأخرى. ما قيمة الزاوية الأصغر؟', '[{"id":"a","text":"60°"},{"id":"b","text":"30°"},{"id":"c","text":"90°"},{"id":"d","text":"45°"}]'::jsonb, 'd', 'نُسمّي الزاويتَين x وy مع x = 3y. الجملة: x + y = 180 و x = 3y. بالتعويض: 3y + y = 180، 4y = 180، y = 45°. الزاوية الكبرى هي x = 135°. التحقّق: 135 + 45 = 180 ✓، 135 = 3×45 ✓.', 5),
  ('13d3926a-0976-5989-9f7c-1cd036bcd326', 'b6fdc318-4fb8-5cdf-a865-2ffd1468c8b7', 'سجّل معلّم علامات 5 تلاميذ في مادّة الرياضيات: 8 ، 12 ، 15 ، 10 ، 10. ما هو المعدّل الحسابي لهذه العلامات؟', '[{"id":"a","text":"10"},{"id":"b","text":"11"},{"id":"c","text":"12"},{"id":"d","text":"9"}]'::jsonb, 'b', 'المعدّل الحسابي = مجموع القيم ÷ عددها. المجموع = 8 + 12 + 15 + 10 + 10 = 55، وعدد القيم 5، إذن المعدّل = 55 ÷ 5 = 11. تحقّق: 11 يقع بين أصغر علامة (8) وأكبرها (15) كما هو متوقّع.', 1),
  ('9778e81d-5484-5cc2-ae1d-0b4b62056bbd', 'b6fdc318-4fb8-5cdf-a865-2ffd1468c8b7', 'في السلسلة ذاتها: 8 ، 10 ، 10 ، 12 ، 15. ما هو المنوال؟', '[{"id":"a","text":"15"},{"id":"b","text":"8"},{"id":"c","text":"12"},{"id":"d","text":"10"}]'::jsonb, 'd', 'المنوال هو القيمة الأعلى تكرارًا في السلسلة. نعدّ التكرارات: 8 مرّة واحدة، 10 مرّتين، 12 مرّة، 15 مرّة. أعلى تكرار هو 2 ويقابله العدد 10، إذن المنوال = 10.', 2),
  ('99dd9b8d-c6cf-551f-b96d-97c7cdbddb7f', 'b6fdc318-4fb8-5cdf-a865-2ffd1468c8b7', 'في فصل من 40 تلميذًا، حصل 10 تلاميذ على علامة 14. ما هو التواتر بالمائة لعلامة 14؟', '[{"id":"a","text":"20 %"},{"id":"b","text":"14 %"},{"id":"c","text":"40 %"},{"id":"d","text":"25 %"}]'::jsonb, 'd', 'التواتر هو نسبة تكرار القيمة إلى التكرار الكلّي: f = n_i ÷ n = 10 ÷ 40 = 0.25. نحوّله إلى نسبة مئوية بالضرب في 100: 0.25 × 100 = 25 %. تحقّق: 25 % من 40 = 10 تلاميذ ✓.', 4),
  ('70c72520-1938-5ed8-9f18-589953b27100', 'b6fdc318-4fb8-5cdf-a865-2ffd1468c8b7', 'في تمثيل بيانيّ على شكل قطاع دائري، فئة تمثّل 40 % من المجتمع. ما هي زاوية القطاع المقابل لها؟', '[{"id":"a","text":"40°"},{"id":"b","text":"144°"},{"id":"c","text":"120°"},{"id":"d","text":"80°"}]'::jsonb, 'b', 'القطاع الدائري يوزّع 360° بحسب التواتر: زاوية القطاع = f_i × 360°. هنا f_i = 40 % = 0.40، إذن الزاوية = 0.40 × 360° = 144°. تحقّق: 144° ÷ 360° = 0.40 = 40 % ✓.', 5),
  ('4c206254-1a5d-5f89-9405-19436cb62a41', '7880a5ae-03cb-524b-aef9-ff8c1bb9b85b', 'علامات 6 تلاميذ مرتّبة تصاعديًّا: 5 ، 9 ، 9 ، 11 ، 13 ، 13. ما هو المعدّل الحسابي؟', '[{"id":"a","text":"10"},{"id":"b","text":"9"},{"id":"c","text":"11"},{"id":"d","text":"10.5"}]'::jsonb, 'a', 'المعدّل الحسابي = مجموع القيم ÷ عددها. المجموع = 5 + 9 + 9 + 11 + 13 + 13 = 60، وعدد القيم 6، إذن المعدّل = 60 ÷ 6 = 10. تحقّق: 10 يقع ضمن المدى [5 ، 13] ✓.', 1),
  ('ac35bf2e-668e-5f5f-9d8f-b2c572a3747a', '7880a5ae-03cb-524b-aef9-ff8c1bb9b85b', 'في فصل من 60 تلميذًا، حصل 15 تلميذًا على علامة 10. ما هي زاوية القطاع الدائري المقابل لهذه الفئة؟', '[{"id":"a","text":"60°"},{"id":"b","text":"54°"},{"id":"c","text":"90°"},{"id":"d","text":"36°"}]'::jsonb, 'c', 'نحسب أوّلًا التواتر = التكرار ÷ التكرار الكلّي = 15 ÷ 60 = 0.25. ثمّ زاوية القطاع = التواتر × 360° = 0.25 × 360° = 90°. تحقّق: 90° هي ربع الدائرة، وفعلًا 15 تلميذًا = ربع الـ60 ✓.', 4),
  ('0f58c292-0423-585e-8b48-f312610e77c9', '93d7ec3c-499d-5401-afbd-44d801bd6165', 'صورة المثلث ABC بالانسحاب ذي الشعاع $\overrightarrow{AB}$ هي المثلث A''B''C''. ماذا يساوي $\overrightarrow{AA''}$؟', '[{"id":"a","text":"$\\overrightarrow{AC}$"},{"id":"b","text":"$\\overrightarrow{BA}$"},{"id":"c","text":"$\\overrightarrow{AB}$"},{"id":"d","text":"$\\overrightarrow{0}$"}]'::jsonb, 'c', 'في الانسحاب ذي الشعاع $\overrightarrow{AB}$، كلّ نقطة M تنتقل بحيث $\overrightarrow{MM''} = \overrightarrow{AB}$. وبما أنّ A تنتقل إلى A''، فإنّ $\overrightarrow{AA''} = \overrightarrow{AB}$. أمّا الخيارات الأخرى فخاطئة: $\overrightarrow{BA}$ معاكسٌ له، و$\overrightarrow{AC}$ شعاعٌ آخر، و$\overrightarrow{0}$ يعني انعدام الانتقال.', 3),
  ('f938f51c-9d1e-5da4-b531-8b543a4792c2', 'c0f4caab-6fe4-5cc1-9698-141918f14e73', 'موشور قائم قاعدته مستطيل طوله 5 cm وعرضه 3 cm وارتفاعه 4 cm. ما حجمه؟', '[{"id":"a","text":"60 cm³"},{"id":"b","text":"45 cm³"},{"id":"c","text":"30 cm³"},{"id":"d","text":"20 cm³"}]'::jsonb, 'a', 'حجم الموشور القائم = مساحة القاعدة × الارتفاع. القاعدة مستطيل مساحته $5 \times 3 = 15 \text{ cm}^2$، إذن $V = 15 \times 4 = 60 \text{ cm}^3$. تنبيه: نحسب مساحة القاعدة أوّلًا ثمّ نضربها في الارتفاع.', 1),
  ('cd3dc54f-1c0c-598c-8515-f4773e66e73f', 'c0f4caab-6fe4-5cc1-9698-141918f14e73', 'أسطوانة نصف قطرها 3 cm وارتفاعها 4 cm. ما حجمها؟ (π ≈ 3.14)', '[{"id":"a","text":"37.68 cm³"},{"id":"b","text":"75.36 cm³"},{"id":"c","text":"113.04 cm³"},{"id":"d","text":"150.72 cm³"}]'::jsonb, 'c', 'حجم الأسطوانة = مساحة القاعدة الدائرية × الارتفاع = $\pi r^2 h$. نربّع نصف القطر أوّلًا: $r^2 = 3^2 = 9$، إذن $V = 3.14 \times 9 \times 4 = 3.14 \times 36 = 113.04 \text{ cm}^3$. انتبه: نربّع نصف القطر r وليس القطر.', 3),
  ('546ec25e-87b5-5290-bf81-399849944cf6', 'c0f4caab-6fe4-5cc1-9698-141918f14e73', 'مخروط نصف قطر قاعدته 3 cm وارتفاعه 4 cm. ما حجمه؟ (π ≈ 3.14)', '[{"id":"a","text":"113.04 cm³"},{"id":"b","text":"75.36 cm³"},{"id":"c","text":"37.68 cm³"},{"id":"d","text":"25.12 cm³"}]'::jsonb, 'c', 'حجم المخروط = ثلث حجم الأسطوانة ذات القاعدة والارتفاع نفسهما: $V = \frac{1}{3} \pi r^2 h$. نحسب $\pi r^2 h = 3.14 \times 9 \times 4 = 113.04$، ثمّ نأخذ الثلث: $V = \frac{1}{3} \times 113.04 = 37.68 \text{ cm}^3$.', 5),
  ('bc3acdeb-df34-5d99-827b-46cad1675a03', 'c0f4caab-6fe4-5cc1-9698-141918f14e73', 'ما مساحة سطح كرة نصف قطرها 5 cm؟ (π ≈ 3.14)', '[{"id":"a","text":"78.5 cm²"},{"id":"b","text":"314 cm²"},{"id":"c","text":"523.33 cm²"},{"id":"d","text":"157 cm²"}]'::jsonb, 'b', 'مساحة سطح الكرة = $4\pi r^2$. نربّع نصف القطر: $r^2 = 5^2 = 25$، إذن $S = 4 \times 3.14 \times 25 = 314 \text{ cm}^2$. انتبه إلى التمييز: $4\pi r^2$ هي المساحة، أمّا الحجم فهو $\frac{4}{3}\pi r^3$.', 6),
  ('eca58638-841d-588b-9108-5ed680a14f01', '00789172-89dd-5cc2-8af9-730645c3c113', 'أسطوانة نصف قطرها 5 cm وارتفاعها 8 cm. ما حجمها؟ (π ≈ 3.14)', '[{"id":"a","text":"314 cm³"},{"id":"b","text":"502.4 cm³"},{"id":"c","text":"628 cm³"},{"id":"d","text":"251.2 cm³"}]'::jsonb, 'c', 'حجم الأسطوانة = مساحة القاعدة الدائرية × الارتفاع = $\pi r^2 h$. نربّع نصف القطر: $r^2 = 5^2 = 25$، إذن $V = 3.14 \times 25 \times 8 = 3.14 \times 200 = 628 \text{ cm}^3$.', 1),
  ('cfca19fb-620b-5f95-9212-1b6ef4bfafcf', '00789172-89dd-5cc2-8af9-730645c3c113', 'مخروط نصف قطر قاعدته 6 cm وارتفاعه 9 cm. ما حجمه؟ (π ≈ 3.14)', '[{"id":"a","text":"1017.36 cm³"},{"id":"b","text":"678.24 cm³"},{"id":"c","text":"169.56 cm³"},{"id":"d","text":"339.12 cm³"}]'::jsonb, 'd', 'حجم المخروط = ثلث حجم الأسطوانة المقابلة: $V = \frac{1}{3}\pi r^2 h$. نربّع نصف القطر: $r^2 = 6^2 = 36$، ونحسب $\pi r^2 h = 3.14 \times 36 \times 9 = 1017.36$، ثمّ نأخذ الثلث: $V = \frac{1}{3} \times 1017.36 = 339.12 \text{ cm}^3$.', 2),
  ('aabce6d4-f8ce-58d2-8737-80d73b3f05c8', '3b342ef2-05e7-53d3-bded-effe80517ef5', 'Mets le sujet en relief : « Le héros sauve le village. »', '[{"id":"a","text":"C''est le village que le héros sauve."},{"id":"b","text":"C''est le héros qui sauve le village."},{"id":"c","text":"Le village est sauvé par le héros."},{"id":"d","text":"Le héros sauve-t-il le village ?"}]'::jsonb, 'b', 'Pour mettre le SUJET en relief, on emploie le présentatif « c''est… qui » : « C''est le héros qui sauve le village. » L''option a (« c''est… que ») met en relief le COD ; l''option c est une transformation passive ; l''option d est une interrogation.', 6),
  ('c124cc25-0734-5a92-811e-669baf60fa4b', '7a24537c-05b2-5498-864c-768a4f7b3ee8', 'Laquelle de ces phrases est au discours direct ?', '[{"id":"a","text":"Le professeur dit qu''ils ouvrent leurs cahiers."},{"id":"b","text":"Le professeur leur ordonne d''ouvrir leurs cahiers."},{"id":"c","text":"Le professeur dit : « Ouvrez vos cahiers. »"},{"id":"d","text":"Le professeur demande si les cahiers sont ouverts."}]'::jsonb, 'c', 'Le discours direct reproduit les paroles telles quelles, annoncées par les deux-points et encadrées par des guillemets : c''est l''option c. Les options a, b et d intègrent les paroles dans une subordonnée (« qu''ils ouvrent », « d''ouvrir », « si… ») : ce sont des discours indirects.', 1),
  ('789d8fb4-ef9b-57a5-971b-67821be37f1a', 'a929d5d0-6d99-542b-8482-d7e65feeb3b3', 'Transforme entièrement au discours indirect :
Le chevalier dit : « Je partirai demain à l''aube. »
Le chevalier dit qu''il ___.', '[{"id":"a","text":"partira demain à l''aube"},{"id":"b","text":"partirait demain à l''aube"},{"id":"c","text":"partait le lendemain à l''aube"},{"id":"d","text":"partirait le lendemain à l''aube"}]'::jsonb, 'd', 'Le verbe introducteur « dit » est au passé simple : le futur simple « partirai » devient conditionnel présent « partirait », et l''indicateur de temps « demain » se transforme en « le lendemain » au discours indirect. D''où la réponse d (« partirait le lendemain à l''aube »). L''option a n''opère aucun des deux changements ; l''option b change le temps mais garde « demain » ; l''option c change l''indicateur mais emploie l''imparfait au lieu du conditionnel.', 2),
  ('927e93ec-4461-53b5-9378-38ef71fbb9b2', 'a929d5d0-6d99-542b-8482-d7e65feeb3b3', 'Transforme au discours indirect :
Elle demanda : « Qu''est-ce qui fait ce bruit ? »
Elle demanda ___.', '[{"id":"a","text":"ce que faisait ce bruit"},{"id":"b","text":"ce qui faisait ce bruit"},{"id":"c","text":"qu''est-ce qui faisait ce bruit"},{"id":"d","text":"si quelque chose faisait ce bruit"}]'::jsonb, 'b', '« Qu''est-ce qui » (sujet) se transforme en « ce qui » au discours indirect, d''où la réponse b. Le verbe introducteur « demanda » étant au passé, le présent « fait » devient imparfait « faisait ». L''option a emploie « ce que », réservé au COD (et non au sujet) ; l''option c conserve « qu''est-ce qui », forme directe interdite au DI ; l''option d (« si ») transforme à tort la question partielle en question totale et altère le sens.', 3),
  ('7b7368b8-68e7-5388-a30c-503e4d1dc5dd', 'a929d5d0-6d99-542b-8482-d7e65feeb3b3', 'Dans la phrase au discours indirect : « Le guide nous expliqua qu''il avait visité ce site l''année précédente. », quel était le discours direct d''origine ?', '[{"id":"a","text":"« J''avais visité ce site l''année précédente. »"},{"id":"b","text":"« Je visiterai ce site l''année prochaine. »"},{"id":"c","text":"« J''ai visité ce site l''année dernière. »"},{"id":"d","text":"« Je visite ce site l''année dernière. »"}]'::jsonb, 'c', 'Au DI, le verbe introducteur « expliqua » est au passé : le plus-que-parfait « avait visité » remonte au passé composé « a visité » dans le DD, et l''indicateur « l''année précédente » redevient « l''année dernière ». La réponse est donc c. L''option a reprend telle quelle la forme du DI (plus-que-parfait + « l''année précédente »), au lieu de restituer le DD ; l''option b emploie le futur, qui aurait donné un conditionnel au DI ; l''option d emploie le présent, incompatible avec « avait visité ».', 5),
  ('f2f3c849-25e9-53d0-b09e-4eff720714b2', 'b89d641c-95d4-5820-875a-3bac22a2add4', 'Quel emploi de l''impératif est illustré dans : « Prends soin de toi. » ?', '[{"id":"a","text":"Un fait réel"},{"id":"b","text":"Une hypothèse"},{"id":"c","text":"Un conseil"},{"id":"d","text":"Un doute"}]'::jsonb, 'c', 'Le ton de « Prends soin de toi » est bienveillant : c''est un conseil (réponse c), pas un ordre autoritaire. L''impératif peut exprimer un ordre, un conseil ou une prière. Les autres valeurs proposées relèvent d''autres modes : le fait réel (a) de l''indicatif, l''hypothèse (b) du conditionnel et le doute (d) du subjonctif.', 2),
  ('a2241625-9fa9-504f-841d-0b346289ca00', 'b89d641c-95d4-5820-875a-3bac22a2add4', 'Quelle forme verbale est correcte dans : « Si tu ___ davantage, tu réussirais. » ?', '[{"id":"a","text":"travaillerais"},{"id":"b","text":"travaillais"},{"id":"c","text":"travailleras"},{"id":"d","text":"travailles"}]'::jsonb, 'b', 'Après « si » dans une hypothèse, on emploie l''imparfait (jamais le conditionnel) : « si tu travaillais → tu réussirais ». La structure est : si + imparfait → conditionnel présent ; la réponse est donc b (« travaillais »). Les options a (conditionnel), c (futur) et d (présent) sont toutes interdites après « si » dans ce contexte.', 6),
  ('1b86b32d-c59d-5d28-a86e-a87b3cd41919', '7efc2dc4-09b3-576b-b2f2-78e7a6288526', 'Quelle phrase illustre correctement l''emploi du conditionnel de politesse ?', '[{"id":"a","text":"Je veux un renseignement, s''il vous plaît."},{"id":"b","text":"Je voudrais un renseignement, s''il vous plaît."},{"id":"c","text":"Je voulus un renseignement, s''il vous plaît."},{"id":"d","text":"Je veuille un renseignement, s''il vous plaît."}]'::jsonb, 'b', '« Je voudrais » est le conditionnel présent de « vouloir » : il adoucit la demande et exprime la politesse (réponse b). L''option a (« je veux », présent de l''indicatif) est plus directe et moins polie ; c (« je voulus », passé simple) est inapproprié ici ; d (« je veuille ») emploie à tort le subjonctif dans un contexte où le conditionnel s''impose.', 1),
  ('1f4296d8-c07e-5e6d-b599-0022c8f72118', '7efc2dc4-09b3-576b-b2f2-78e7a6288526', 'Conjugue correctement au subjonctif présent (3e personne du singulier) :
« Il est indispensable que le groupe ___ à l''heure. »
(verbe : venir)', '[{"id":"a","text":"vient"},{"id":"b","text":"viendra"},{"id":"c","text":"vienne"},{"id":"d","text":"venait"}]'::jsonb, 'c', 'Après « il est indispensable que », on emploie le subjonctif présent. Le radical se prend sur la 3e personne du pluriel du présent de l''indicatif (« ils viennent » → « vienn- ») : qu''il vienne (réponse c). L''option a (« vient ») est le présent de l''indicatif, b (« viendra ») le futur, d (« venait ») l''imparfait.', 5),
  ('b290332e-4669-578d-9720-28fb55d9139b', 'e0728ce7-0202-5fc6-a5ec-566c51e9dc5d', 'في «جاءَ الطالبُ»، ما علامة رفع الفاعل «الطالبُ»؟', '[{"id":"a","text":"الضمّة"},{"id":"b","text":"الفتحة"},{"id":"c","text":"الكسرة"},{"id":"d","text":"السكون"}]'::jsonb, 'a', '«الطالبُ» فاعل لأنّه مَن قام بفعل المجيء، والفاعل حكمه الرفع دائمًا. وهو اسم مفرد، فعلامة رفعه الضمّة الظاهرة على آخره وهي العلامة الأصلية للرفع. ولا يصحّ نصبه بالفتحة ولا جرّه بالكسرة لأنّه ليس مفعولًا ولا مجرورًا.', 2),
  ('fd04e6f9-f99e-53b0-bf97-e17f875d086d', 'e0728ce7-0202-5fc6-a5ec-566c51e9dc5d', 'ما العلامة الأصلية للجرّ في الاسم المفرد؟', '[{"id":"a","text":"الفتحة"},{"id":"b","text":"الضمّة"},{"id":"c","text":"السكون"},{"id":"d","text":"الكسرة"}]'::jsonb, 'd', 'العلامة الأصلية للجرّ في الاسم المفرد المنصرف هي الكسرة الظاهرة على آخره، نحو «مررتُ بالطالبِ» حيث جُرّ «الطالبِ» بالكسرة. أمّا الفتحة فعلامة فرعية للجرّ في الممنوع من الصرف، والضمّة والسكون فليستا من علامات الجرّ أصلًا.', 4),
  ('42fee5e6-ebba-59f2-8bbb-b082518abb07', 'acd6eb5c-3981-5b02-bf6d-8df8daf6641f', 'في جملة «الأمانةَ يا صديقي»، ما الأساليب النحوية الواردة فيها وما إعراب «صديقي»؟', '[{"id":"a","text":"أسلوب تحذير فقط؛ «صديقي»: منادى مضاف منصوب بالفتحة المقدَّرة"},{"id":"b","text":"أسلوب اختصاص فقط؛ «صديقي»: منصوب على الاختصاص"},{"id":"c","text":"أسلوب إغراء فقط؛ «صديقي»: مضاف إليه مجرور بالكسرة"},{"id":"d","text":"أسلوبا إغراء ونداء معًا؛ «صديقي»: منادى مضاف منصوب وعلامة نصبه الفتحة المقدَّرة على ما قبل الياء"}]'::jsonb, 'd', 'تجمع الجملة أسلوبَين: «الأمانةَ» إغراء (مُغرى به منصوب بفعل محذوف وجوبًا تقديره «الزَم») يحثّ المخاطَب على التمسّك بالأمانة، و«يا صديقي» نداء. «صديقي» منادى مضاف منصوب وعلامة نصبه الفتحة المقدَّرة على ما قبل ياء المتكلّم، منَع من ظهورها اشتغالُ المحلّ بحركة المناسبة، والياء ضمير متّصل مضاف إليه في محلّ جرّ.', 5),
  ('439a46cb-44b9-5308-8d2d-e66deb1fee1b', '9b5c21ee-37e3-50d8-a7c5-ba6a75e2eb01', 'ما وزن اسم الفاعل من الفعل الثلاثي «نَصَرَ»؟', '[{"id":"a","text":"مَفعُول (مَنصُور)"},{"id":"b","text":"فَاعِل (نَاصِر)"},{"id":"c","text":"مِفعَال (مِنصَار)"},{"id":"d","text":"فَعِيل (نَصِير)"}]'::jsonb, 'b', 'اسم الفاعل من الثلاثي يُصاغ قياسًا على وزن «فَاعِل»، فمن «نَصَرَ» نقول «نَاصِر» (من وقع منه النصر). أمّا «مَنصُور» فاسم مفعول (وزن مَفعُول)، و«نَصِير» صفة مشبّهة (فَعِيل)، و«مِنصَار» وزن غير مستعمل لاسم الفاعل.', 1),
  ('1b1bab6b-e7bb-596b-83b3-c57f76830710', '9b5c21ee-37e3-50d8-a7c5-ba6a75e2eb01', 'أيّ الكلمات التالية اسم مفعول صحيح؟', '[{"id":"a","text":"مَكتُوب"},{"id":"b","text":"كَاتِب"},{"id":"c","text":"كَتِيب"},{"id":"d","text":"مِكتَاب"}]'::jsonb, 'a', 'اسم المفعول من الثلاثي يُصاغ على وزن «مَفعُول»، و«مَكتُوب» على هذا الوزن من «كَتَبَ» فهو يدلّ على ما وقع عليه فعل الكتابة. أمّا «كَاتِب» فاسم فاعل (فَاعِل)، و«مِكتَاب» اسم آلة (مِفعَال)، و«كَتِيب» ليس مشتقًّا قياسيًّا لاسم المفعول.', 2),
  ('3a57be27-7b78-5492-82bc-e73906a3416b', '9b5c21ee-37e3-50d8-a7c5-ba6a75e2eb01', 'ما وزن اسم التفضيل من الفعل «حَسُنَ»؟', '[{"id":"a","text":"أَفعَل (أَحسَن)"},{"id":"b","text":"مَفعُول (مَحسُون)"},{"id":"c","text":"فَاعِل (حَاسِن)"},{"id":"d","text":"فَعِيل (حَسِين)"}]'::jsonb, 'a', 'اسم التفضيل يُصاغ من الثلاثي على وزن «أَفعَل» للدلالة على أنّ شيئًا زاد على غيره في الصفة؛ فمن «حَسُنَ» نقول «أَحسَن» أي أزيد حُسنًا. أمّا «مَحسُون» فليس مستعملًا، و«حَاسِن» اسم فاعل، و«حَسِين» صفة مشبّهة — ولا يدلّ أيٌّ منها على التفضيل.', 3),
  ('9d12af42-8ca0-5491-98cd-9573549b60f0', '9b5c21ee-37e3-50d8-a7c5-ba6a75e2eb01', 'ما نوع الكلمة «مُدَرِّس» في الجملة «المُدَرِّسُ شرحَ الدرسَ»؟', '[{"id":"a","text":"اسم مفعول من غير الثلاثي"},{"id":"b","text":"اسم فاعل من غير الثلاثي (دَرَّسَ)"},{"id":"c","text":"صيغة مبالغة"},{"id":"d","text":"اسم فاعل من الثلاثي"}]'::jsonb, 'b', 'اسم الفاعل من غير الثلاثي يُصاغ من مضارعه بإبدال حرف المضارعة ميمًا مضمومة وكسر ما قبل الآخر؛ فمن «دَرَّسَ ← يُدَرِّس» نقول «مُدَرِّس» بكسر الراء (ما قبل الآخر)، وهو هنا فاعل الفعل «شرحَ» (الذي درّس وشرح). ولو فُتح ما قبل آخره (مُدَرَّس) لصار اسم مفعول، فالكسرة هي التي عيّنته اسمَ فاعل لا اسمَ مفعول ولا صيغةَ مبالغة.', 4),
  ('1dae3eb0-f7f5-5e50-9fd4-46388fd6f95d', '9b5c21ee-37e3-50d8-a7c5-ba6a75e2eb01', 'أيّ الأوزان التالية يدلّ على صيغة مبالغة للكثرة والشدّة؟', '[{"id":"a","text":"فَاعِل (صَائِم)"},{"id":"b","text":"مَفعُول (مَصُوم)"},{"id":"c","text":"مَفعَل (مَصَام)"},{"id":"d","text":"فَعَّال (صَوَّام)"}]'::jsonb, 'd', 'صيغة المبالغة تدلّ على كثرة الفعل وشدّته، ومن أشهر أوزانها «فَعَّال»؛ فـ«صَوَّام» على هذا الوزن تدلّ على كثرة الصيام (لا مجرّد فاعله). أمّا «صَائِم» فاسم فاعل (فَاعِل) يدلّ على الفعل دون مبالغة، و«مَصُوم» و«مَصَام» ليسا من أوزان المبالغة.', 5),
  ('d3014313-a3b3-5e0f-be7b-750a2cedd9d9', '9b5c21ee-37e3-50d8-a7c5-ba6a75e2eb01', 'أيّ الكلمات التالية اسم آلة على وزن مِفعَال؟', '[{"id":"a","text":"مِبرَد"},{"id":"b","text":"مِفتَاح"},{"id":"c","text":"مِكنَسة"},{"id":"d","text":"مِقصَّ"}]'::jsonb, 'b', 'اسم الآلة يُصاغ على ثلاثة أوزان قياسية: مِفعَال ومِفعَل ومِفعَلة. و«مِفتَاح» على وزن «مِفعَال» (الميم زائدة والفاء-التاء-الحاء من جذر فَتَحَ)، فهو أداة الفتح. أمّا «مِبرَد» فعلى مِفعَل، و«مِكنَسة» على مِفعَلة، و«مِقصّ» على مِفعَل — فالمطابق لوزن مِفعَال هو «مِفتَاح» وحده.', 6),
  ('6242b042-aeb4-54d4-b948-bd97235a8a5c', '88a20df0-483f-51e9-b7a2-ca4a3ea0ddc2', 'الكلمة «صَبُور» على أيّ وزن من أوزان صيغ المبالغة؟', '[{"id":"a","text":"فَعَّال"},{"id":"b","text":"مِفعَال"},{"id":"c","text":"فَعِيل"},{"id":"d","text":"فَعُول"}]'::jsonb, 'd', '«صَبُور» على وزن «فَعُول» (الصاد فاء والباء عين والراء لام من جذر صَبَرَ)، وهو من أوزان صيغة المبالغة الدالّة على شدّة الصبر وكثرته لا مجرّد حصوله. ولا يصحّ «فَعَّال» (وزنه صَبَّار وهو موجود لكنّه ليس صورة الكلمة هنا) ولا «مِفعَال» ولا «فَعِيل»، لأنّ بنية «صَبُور» تطابق فَعُول بعينه.', 1),
  ('ad6d74ec-bdef-5b47-926d-d90644216455', '88a20df0-483f-51e9-b7a2-ca4a3ea0ddc2', 'أيّ الكلمات التالية اسم زمان أو مكان؟', '[{"id":"a","text":"مَجلِس"},{"id":"b","text":"جَالِس"},{"id":"c","text":"مَجلُوس"},{"id":"d","text":"جَلَّاس"}]'::jsonb, 'a', 'اسم الزمان والمكان من الثلاثي يُصاغ على «مَفعَل» أو «مَفعِل»؛ و«مَجلِس» على وزن «مَفعِل» (كُسرت عينه لأنّ مضارعه «يَجلِس» مكسور العين)، ويدلّ على مكان الجلوس. أمّا «جَالِس» فاسم فاعل، و«مَجلُوس» اسم مفعول، و«جَلَّاس» صيغة مبالغة — فلا يدلّ أيٌّ منها على المكان.', 2),
  ('7e0f1c35-7a2c-5d87-94c8-3a9c136d6243', '88a20df0-483f-51e9-b7a2-ca4a3ea0ddc2', 'الكلمة «مِكنَسة» على أيّ وزن من أوزان اسم الآلة؟', '[{"id":"a","text":"مِفعَلة"},{"id":"b","text":"مِفعَال"},{"id":"c","text":"مِفعَل"},{"id":"d","text":"فَعَّال"}]'::jsonb, 'a', '«مِكنَسة» على وزن «مِفعَلة» (الميم زائدة، والكاف-النون-السين من جذر كَنَسَ، ثمّ تاء التأنيث)، وهو أحد أوزان اسم الآلة القياسية الثلاثة (مِفعَال، مِفعَل، مِفعَلة) فهي أداة الكَنس. ولا يطابقها مِفعَال (مِكناس) ولا مِفعَل (مِكنَس) ولا فَعَّال، لأنّ ختمها بالتاء يُعيّن وزن مِفعَلة.', 3),
  ('a8cdd2d6-aaae-54bf-841a-cceeb408a7ed', '88a20df0-483f-51e9-b7a2-ca4a3ea0ddc2', 'في الجملة «المُستَعمَلُ بِعنايةٍ يدومُ طويلًا»، ما نوع كلمة «المُستَعمَل»؟', '[{"id":"a","text":"اسم فاعل من «استَعمَلَ»"},{"id":"b","text":"اسم مفعول من «استَعمَلَ» (سداسي)"},{"id":"c","text":"صفة مشبّهة"},{"id":"d","text":"اسم زمان"}]'::jsonb, 'b', 'اسم المفعول من غير الثلاثي يُصاغ من مضارعه بميم مضمومة مكان حرف المضارعة وفتح ما قبل الآخر؛ فمن «استَعمَلَ ← يُستَعمَل» نقول «مُستَعمَل» بفتح الميم الثانية (ما قبل الآخر)، فهو ما وقع عليه الاستعمال. ولو كُسر ما قبل الآخر (مُستَعمِل) لصار اسم فاعل (مَن يستعمل)، فالفتحة هي الفارق الحاسم هنا.', 4),
  ('e03bd42b-389f-56b8-942e-9e75455368ac', '88a20df0-483f-51e9-b7a2-ca4a3ea0ddc2', 'في «قرأتُ كِتابًا مُثيرًا»، ما نوع «مُثِير»؟', '[{"id":"a","text":"اسم مفعول من الثلاثي"},{"id":"b","text":"اسم فاعل من غير الثلاثي (أَثَارَ)"},{"id":"c","text":"صيغة مبالغة"},{"id":"d","text":"صفة مشبّهة"}]'::jsonb, 'b', '«مُثِير» اسم فاعل من الفعل الرباعي المزيد «أَثَارَ ← يُثِير»، صيغ بميم مضمومة وكسر ما قبل الآخر (الياء)، فدلّ على ما يقوم بالإثارة (الكتاب المثير). ولو فُتح ما قبل آخره (مُثَار) لكان اسم مفعول، وليس صفة مشبّهة لأنّه يدلّ على حدث متجدّد لا صفة ثابتة، ولا صيغة مبالغة لانتفاء وزنها.', 6),
  ('3520e9b6-2c60-5bdb-9452-faf19f751575', '2c90abf4-246f-5ca7-bce2-e8a553e79052', 'أيّ ممّا يلي مصدر ضوئي ثانوي؟', '[{"id":"a","text":"الشمس"},{"id":"b","text":"المصباح المتوهّج"},{"id":"c","text":"القمر"},{"id":"d","text":"اللهب"}]'::jsonb, 'c', 'المصدر الضوئي الأوّلي ينتج الضوء بنفسه (كالشمس والمصباح المتوهّج واللهب)، أمّا المصدر الثانوي فيعكس ضوءًا يتلقّاه من غيره. القمر لا يبعث ضوءًا ذاتيًّا بل يعكس إلينا ضوء الشمس الساقط عليه، لذلك يُصنَّف مصدرًا ضوئيًّا ثانويًّا.', 1),
  ('81f6c3b2-6342-5561-927e-2e6ebed08499', '2c90abf4-246f-5ca7-bce2-e8a553e79052', 'كيف ينتشر الضوء في وسط شفّاف ومتجانس؟', '[{"id":"a","text":"في خطوط منحنية"},{"id":"b","text":"في خطوط مستقيمة"},{"id":"c","text":"في خطوط متعرّجة"},{"id":"d","text":"في دوائر"}]'::jsonb, 'b', 'مبدأ الانتشار المستقيمي للضوء: في وسط شفّاف (ينفذ منه الضوء) ومتجانس (له الخصائص نفسها في كلّ نقطة)، ينتقل الضوء في خطوط مستقيمة دون انحناء. ولهذا نمثّل مساره بشعاع ضوئي مستقيم، وعليه يُفسَّر تكوّن الظلال والكسوف. أمّا إذا تغيّر الوسط فينكسر الضوء ويتغيّر اتّجاهه.', 2),
  ('a617b749-a476-50aa-9d77-27dcf968ea8a', '2c90abf4-246f-5ca7-bce2-e8a553e79052', 'متى نرى جسمًا غير مضيء؟', '[{"id":"a","text":"عندما ينتج الضوء بنفسه"},{"id":"b","text":"في الظلام التامّ"},{"id":"c","text":"عندما يمتصّ كلّ الضوء"},{"id":"d","text":"عندما يصلنا الضوء المنعكس عنه"}]'::jsonb, 'd', 'الجسم غير المضيء لا يبعث ضوءًا ذاتيًّا، فلا يمكن رؤيته في الظلام التامّ. لرؤيته يجب أن يسقط عليه ضوء من مصدر، فيعكسه الجسم في كلّ الاتّجاهات، وحين يصل جزءٌ من هذا الضوء المنعكس إلى أعيننا نراه. إذن الشرط هو وصول الضوء المنعكس عنه إلى العين.', 3),
  ('f5fb35c5-5154-5d48-b3f7-7a390b017440', '2c90abf4-246f-5ca7-bce2-e8a553e79052', 'ما هو «الظلّ المحمول»؟', '[{"id":"a","text":"الجزء غير المضاء من الجسم نفسه"},{"id":"b","text":"الضوء المنعكس عن المرآة"},{"id":"c","text":"مصدر ضوئي ثانوي"},{"id":"d","text":"المنطقة المظلمة المتكوّنة على حاجز خلف الجسم"}]'::jsonb, 'd', 'لأنّ الضوء ينتشر مستقيمًا، يحجب الجسم المعتم الأشعّة فيمنعها من بلوغ منطقة من الحاجز خلفه؛ هذه المنطقة المظلمة على الحاجز هي «الظلّ المحمول». أمّا «ظلّ النفس» فهو الجزء غير المضاء من سطح الجسم نفسه (الوجه البعيد عن المنبع). فالأوّل يقع على الحاجز والثاني على الجسم.', 6),
  ('d88cfa81-9602-5207-baae-4cdb136464a2', '738049b5-6688-53ba-8f47-c5fea00f2b0b', 'يحدث كسوف الشمس عندما:', '[{"id":"a","text":"يتوسّط القمرُ بين الشمس والأرض"},{"id":"b","text":"تتوسّط الأرضُ بين الشمس والقمر"},{"id":"c","text":"تتوسّط الشمسُ بين الأرض والقمر"},{"id":"d","text":"يبتعد القمر عن الأرض"}]'::jsonb, 'a', 'يحدث الكسوف لأنّ الضوء ينتشر مستقيمًا: حين يصطفّ القمر بين الشمس والأرض، يعترض القمر المعتم أشعّة الشمس فيُلقي ظلّه على جزء من الأرض، فيختفي قرص الشمس كليًّا أو جزئيًّا عمّن يقف في منطقة الظلّ. لذلك يكون الكسوف نهارًا والقمر في طور المحاق.', 1),
  ('ae3a8765-e3bc-5de4-aad9-c042423ec09d', '738049b5-6688-53ba-8f47-c5fea00f2b0b', 'يحدث خسوف القمر عندما:', '[{"id":"a","text":"يتوسّط القمر بين الشمس والأرض"},{"id":"b","text":"يكون القمر بدرًا بعيدًا"},{"id":"c","text":"تشرق الشمس والقمر معًا"},{"id":"d","text":"تتوسّط الأرضُ بين الشمس والقمر"}]'::jsonb, 'd', 'حين تتوسّط الأرض بين الشمس والقمر على استقامة واحدة، تحجب الأرضُ المعتمة ضوءَ الشمس فيدخل القمر في ظلّها (المخروط المظلم خلفها)، فيُحرَم من الضوء الذي يعكسه إلينا عادةً ويبدو معتمًا أو محمرًّا. لذلك يقع الخسوف ليلًا والقمر في طور البدر.', 3),
  ('44ddcd17-bb19-5228-ba8b-4211de3562b1', '71b0fee4-b5db-52e4-8e51-14426ab378c6', 'ما الذي يحدث للضوء عند اصطدامه بسطح المرآة المستوية؟', '[{"id":"a","text":"ينفذ عبرها"},{"id":"b","text":"يرتدّ (ينعكس)"},{"id":"c","text":"يُمتصّ كلّيًّا"},{"id":"d","text":"يتوقّف"}]'::jsonb, 'b', 'سطح المرآة العاكس لا يسمح للضوء بالنفاذ خلفه ولا يمتصّه، فالضوء الساقط يرتدّ عنه عائدًا إلى الوسط نفسه؛ هذه الظاهرة هي الانعكاس. ولأنّ السطح أملس ومنتظم يكون الانعكاس منتظمًا فتتكوّن صورة واضحة.', 1),
  ('e5470327-b001-55f1-9629-5301f11c075f', 'd08d38a1-4e65-593c-97ac-fc646167bd6f', 'أين تتكوّن صورة جسم بُعده عن العدسة المجمّعة أكبر من ضعف البُعد البؤري (d > 2f)؟', '[{"id":"a","text":"صورة تخيّلية معتدلة مكبّرة"},{"id":"b","text":"صورة حقيقية مقلوبة مصغّرة"},{"id":"c","text":"لا تتكوّن أيّ صورة"},{"id":"d","text":"صورة حقيقية مقلوبة مكبّرة"}]'::jsonb, 'b', 'حين يكون الجسم بعيدًا (d > 2f)، تتقاطع الأشعّة بعد عبورها العدسة المجمّعة في الجهة المقابلة، فتتكوّن صورة حقيقية يمكن إسقاطها على شاشة، وتكون مقلوبة (لتقاطع الأشعّة) ومصغّرة (لأنّها أقرب إلى العدسة من الجسم). وعلى هذا المبدأ يعمل آلة التصوير وعدسة العين.', 6),
  ('26d1cfe6-94c3-5c57-aeec-d0c5388828e6', 'f431df6e-67d9-56e3-91f5-590546de1fca', 'أيّ الجمل التالية صحيحة حول النيوترون (N) في نموذج الذرّة؟', '[{"id":"a","text":"النيوترونات موجبة الشحنة وتوجد خارج النواة"},{"id":"b","text":"النيوترونات سالبة الشحنة وتدور حول النواة"},{"id":"c","text":"النيوترونات محايدة الشحنة وتوجد داخل النواة"},{"id":"d","text":"النيوترونات هي نفسها الإلكترونات"}]'::jsonb, 'c', 'النيوترونات جسيمات عديمة الشحنة (محايدة) توجد داخل نواة الذرّة إلى جانب البروتونات. أمّا الإلكترونات فسالبة وتدور خارج النواة.', 4),
  ('1f6bacee-755c-5a84-97c4-6cfeb4a30a7d', '07576f0b-3c33-598e-80e6-79b3ce4364ab', 'في التفاعل: C + O₂ → CO₂، ما هي المتفاعلات؟', '[{"id":"a","text":"CO₂ فقط"},{"id":"b","text":"C و CO₂"},{"id":"c","text":"O₂ و CO₂"},{"id":"d","text":"C و O₂"}]'::jsonb, 'd', 'في المعادلة الكيميائية يفصل السهم بين الموادّ الداخلة في التفاعل (المتفاعلات) على يساره والموادّ المتكوّنة (النواتج) على يمينه. هنا الكربون C والأكسجين O₂ على يسار السهم فهما المتفاعلان اللذان يستهلكان، وثاني أكسيد الكربون CO₂ على يمينه فهو الناتج المتكوّن من اتّحادهما.', 1),
  ('55175f89-37f1-5093-be10-635d8cf97a74', '07576f0b-3c33-598e-80e6-79b3ce4364ab', 'أيّ ممّا يلي تحوّل فيزيائي؟', '[{"id":"a","text":"احتراق الورق"},{"id":"b","text":"صدأ الحديد"},{"id":"c","text":"ذوبان الجليد"},{"id":"d","text":"احتراق الميثان"}]'::jsonb, 'c', 'في ذوبان الجليد تتغيّر الحالة الفيزيائية فقط من الصلبة إلى السائلة، لكنّ المادّة تبقى ماءً (H₂O) ولا تتكوّن مادّة جديدة، لذا فهو تحوّل فيزيائي قابل للعكس بالتجميد. أمّا احتراق الورق أو الميثان وصدأ الحديد فتظهر فيها موادّ جديدة مختلفة الخصائص، فهي تحوّلات كيميائية.', 2),
  ('192af321-7e53-5849-900d-cb4c1814f863', '07576f0b-3c33-598e-80e6-79b3ce4364ab', 'ماذا ينصّ قانون انحفاظ الكتلة (لافوازييه)؟', '[{"id":"a","text":"كتلة المتفاعلات = كتلة النواتج"},{"id":"b","text":"كتلة المتفاعلات أكبر من كتلة النواتج"},{"id":"c","text":"كتلة المتفاعلات أصغر من كتلة النواتج"},{"id":"d","text":"تختفي الكتلة أثناء التفاعل"}]'::jsonb, 'a', 'قانون لافوازييه: «لا شيء يُفقَد ولا شيء يُخلَق، كلّ شيء يتحوّل». فأثناء التفاعل لا تختفي الذرّات بل تعيد ترتيب روابطها فقط، لذا يبقى عددها ونوعها ثابتَين، ومن ثَمّ يكون مجموع كتل المتفاعلات مساويًا تمامًا لمجموع كتل النواتج.', 3),
  ('ea79b802-7f5c-5f15-99a8-70d5c96b57b7', '07576f0b-3c33-598e-80e6-79b3ce4364ab', 'تفاعل 4 g من الميثان مع 16 g من الأكسجين تفاعلًا تامًّا. ما كتلة النواتج؟', '[{"id":"a","text":"20 g"},{"id":"b","text":"12 g"},{"id":"c","text":"16 g"},{"id":"d","text":"4 g"}]'::jsonb, 'a', 'بما أنّ التفاعل تامّ، تُستهلك المتفاعلات كاملةً. وبتطبيق قانون انحفاظ الكتلة (كتلة النواتج = كتلة المتفاعلات): كتلة النواتج = 4 g (ميثان) + 16 g (أكسجين) = 20 g.', 4),
  ('b46481cb-0b1f-5b2d-8a3d-a1d7bdc16b37', '107c0650-6e11-5652-b548-d850f77b6e0a', 'صدأ الحديد في الهواء الرطب هو تحوّل:', '[{"id":"a","text":"فيزيائي"},{"id":"b","text":"تغيّر حالة فقط"},{"id":"c","text":"لا تحوّل فيه"},{"id":"d","text":"كيميائي"}]'::jsonb, 'd', 'في الهواء الرطب يتّحد الحديد مع الأكسجين والماء فيتكوّن الصدأ (أكسيد الحديد المميّأ)، وهو مادّة جديدة تختلف في لونها وخصائصها عن الحديد الأصلي. ولأنّه تظهر مادّة جديدة لا يمكن استرجاع الحديد منها بسهولة، فالتحوّل كيميائي لا فيزيائي.', 2),
  ('5fc6de1c-ebe0-5e6e-8fe4-f25fe4e9a09c', '107c0650-6e11-5652-b548-d850f77b6e0a', 'هل المعادلة C + O₂ → CO₂ موزونة؟', '[{"id":"a","text":"لا، ينقص الكربون"},{"id":"b","text":"لا، ينقص الأكسجين"},{"id":"c","text":"نعم، لأنّ عدد ذرّات كلّ عنصر متساوٍ في الطرفين"},{"id":"d","text":"لا يمكن معرفة ذلك"}]'::jsonb, 'c', 'نتحقّق من توازن كلّ عنصر: الكربون يسارًا 1 (في C) ويمينًا 1 (في CO₂) فهو متساوٍ؛ والأكسجين يسارًا 2 (في O₂) ويمينًا 2 (في CO₂) فهو متساوٍ كذلك. وبما أنّ عدد ذرّات كلّ عنصر متساوٍ في الطرفين، فالمعادلة موزونة فعلًا.', 3),
  ('9e8aff14-50ea-5585-9d86-d673d817419c', '107c0650-6e11-5652-b548-d850f77b6e0a', 'ما الموازنة الصحيحة للتفاعل: H₂ + O₂ → H₂O؟', '[{"id":"a","text":"H₂ + O₂ → H₂O"},{"id":"b","text":"2H₂ + O₂ → 2H₂O"},{"id":"c","text":"H₂ + 2O₂ → 2H₂O"},{"id":"d","text":"2H₂ + 2O₂ → 2H₂O"}]'::jsonb, 'b', 'نوازن بتعديل المعاملات حتى يتساوى عدد ذرّات كلّ عنصر في الطرفين (انحفاظ الكتلة). بالصيغة الأصلية يكون الأكسجين 2 يسارًا و1 يمينًا فهي غير موزونة. بوضع 2H₂ + O₂ → 2H₂O نحصل على الهيدروجين: يسار 2×2=4، يمين 2×2=4 ✓؛ والأكسجين: يسار 2، يمين 2×1=2 ✓. إذن المعادلة موزونة.', 5),
  ('07cabb70-9805-5e1d-a27a-644d6106e340', '107c0650-6e11-5652-b548-d850f77b6e0a', 'في CH₄ + 2O₂ → CO₂ + 2H₂O، كم عدد ذرّات الأكسجين في طرف المتفاعلات؟', '[{"id":"a","text":"2"},{"id":"b","text":"3"},{"id":"c","text":"4"},{"id":"d","text":"6"}]'::jsonb, 'c', 'المعامل 2 أمام O₂ يدلّ على جزيئين من الأكسجين، وكلّ جزيء O₂ يحوي ذرّتَين. إذن عدد ذرّات الأكسجين في طرف المتفاعلات = المعامل × عدد الذرّات في الصيغة = 2 × 2 = 4 ذرّات (وهي تساوي ما في طرف النواتج: CO₂ فيها 2 و2H₂O فيها 2، أي 4 أيضًا).', 6),
  ('080d7783-083d-5532-a30c-825175ef6d09', 'c4f248a7-393a-5c6d-b4af-90311f1ae35d', 'Which sentence uses the present simple correctly to express a habit?', '[{"id":"a","text":"She is going to school every day."},{"id":"b","text":"She goes to school every day."},{"id":"c","text":"She go to school every day."},{"id":"d","text":"She has gone to school every day."}]'::jsonb, 'b', '"every day" marks a habit, which takes the present simple. With the third-person singular "she", add -es: she goes. "is going" is present continuous (now); "go" forgets the -es; "has gone" is present perfect (a result), not a habit.', 1),
  ('7241ee79-462b-5b3a-984c-eea640002fb0', '6b8bbba1-76cd-5943-aa66-9d9da0f72492', 'Choose the correct form: "She ___ to school every day."', '[{"id":"a","text":"is going"},{"id":"b","text":"go"},{"id":"c","text":"goes"},{"id":"d","text":"going"}]'::jsonb, 'c', '"every day" signals a repeated habit, so we use the present simple. With the third-person singular "she", we add -es to a verb ending in -o: she goes. "is going" (present continuous) is for actions happening now; "go" forgets the -es needed after she/he/it; "going" alone is not a finite verb.', 1),
  ('7a63341f-b75c-5f33-9964-f0a5e371d967', '6b8bbba1-76cd-5943-aa66-9d9da0f72492', 'Complete: "Look! The baby ___."', '[{"id":"a","text":"cries"},{"id":"b","text":"cry"},{"id":"c","text":"is crying"},{"id":"d","text":"cried"}]'::jsonb, 'c', '"Look!" draws attention to something happening right now, so we use the present continuous (is + -ing): the baby is crying. "cries" and "cry" are present simple (habits, not this moment); "cried" is past simple.', 2),
  ('43bd124a-3273-5b3d-babe-7c21c893d954', '6b8bbba1-76cd-5943-aa66-9d9da0f72492', 'Which word signals the present simple?', '[{"id":"a","text":"usually"},{"id":"b","text":"now"},{"id":"c","text":"at the moment"},{"id":"d","text":"Look!"}]'::jsonb, 'a', 'Adverbs of frequency such as "usually" describe how often something happens, so they signal a habit and the present simple. By contrast, "now", "at the moment", and "Look!" all point to an action in progress and go with the present continuous.', 3),
  ('c4629643-cb37-5769-8cef-57760b3611f9', '6b8bbba1-76cd-5943-aa66-9d9da0f72492', 'Complete: "He ___ football on Sundays."', '[{"id":"a","text":"play"},{"id":"b","text":"plays"},{"id":"c","text":"is play"},{"id":"d","text":"playing"}]'::jsonb, 'b', '"on Sundays" signals a regular habit, so we use the present simple. The third-person singular "he" adds -s to the verb: he plays. "play" is missing the -s; "is play" mixes two verb forms; "playing" alone cannot be the main verb without am/is/are.', 4),
  ('a5481854-86d1-56f3-8ac1-c1496af746ac', '6b8bbba1-76cd-5943-aa66-9d9da0f72492', 'Choose the correct sentence:', '[{"id":"a","text":"I know the answer."},{"id":"b","text":"I am knowing the answer."},{"id":"c","text":"I knows the answer."},{"id":"d","text":"I am know the answer."}]'::jsonb, 'a', '"know" is a stative verb (a mental state, not an action), so it is not used in the continuous: "I am knowing" is wrong. With "I" we use the base form with no -s, so "I knows" is also wrong, and "I am know" mixes two verbs. The correct sentence is the simple present: I know the answer.', 6),
  ('d8b38f06-1764-5f19-ba99-8f0fd06fd79b', '458c297a-6ea2-522c-9a6c-6dc0c6c7267b', 'Complete: "I can''t talk now, I ___ dinner."', '[{"id":"a","text":"cook"},{"id":"b","text":"cooks"},{"id":"c","text":"am cooking"},{"id":"d","text":"cooked"}]'::jsonb, 'c', '"I can''t talk now" tells us the action is in progress at this moment, so we use the present continuous: I am cooking dinner. "cook"/"cooks" are present simple (habits), and "cooked" is past simple.', 1),
  ('620f8003-045f-50cd-a9f5-2e24398d3bc5', '458c297a-6ea2-522c-9a6c-6dc0c6c7267b', 'Choose the correct form: "Water ___ at 100 degrees."', '[{"id":"a","text":"boils"},{"id":"b","text":"is boiling"},{"id":"c","text":"boil"},{"id":"d","text":"are boiling"}]'::jsonb, 'a', 'A scientific fact or general truth always takes the present simple: water boils at 100 degrees. "is boiling" would mean it is happening at this moment, not always; "boil" forgets the -s for the singular subject "water"; "are boiling" wrongly treats "water" as plural.', 2),
  ('535f555e-00ec-541c-9430-c8c68f6f8bb0', '458c297a-6ea2-522c-9a6c-6dc0c6c7267b', 'Choose the correct negative: "She ___ coffee."', '[{"id":"a","text":"don''t drink"},{"id":"b","text":"isn''t drink"},{"id":"c","text":"not drinks"},{"id":"d","text":"doesn''t drink"}]'::jsonb, 'd', 'In the present simple negative for he/she/it, the auxiliary "does" carries the -s, so the main verb stays in its base form: she doesn''t drink coffee. "don''t drink" uses the wrong auxiliary for "she"; "isn''t drink" mixes "be" with a base verb; "not drinks" has no auxiliary at all.', 3),
  ('71117f1e-36c4-5a8e-b723-9dbc88418bf1', '458c297a-6ea2-522c-9a6c-6dc0c6c7267b', 'Complete the question: "___ they live in Tunis?"', '[{"id":"a","text":"Does"},{"id":"b","text":"Do"},{"id":"c","text":"Are"},{"id":"d","text":"Is"}]'::jsonb, 'b', 'Present simple questions use "do/does" as the auxiliary. With the plural subject "they" we use "Do" + base verb: Do they live...? "Does" is only for he/she/it; "Are"/"Is" would be needed for the present continuous (Are they living...?), not the present simple.', 4),
  ('b5fe6ca3-0ae0-5d0a-becc-64b5e9be71c2', '285d360a-8465-518f-990c-916004f4f3b5', 'Which sentence uses the past simple correctly with an irregular verb?', '[{"id":"a","text":"She goed to the market yesterday."},{"id":"b","text":"She went to the market yesterday."},{"id":"c","text":"She has went to the market yesterday."},{"id":"d","text":"She was go to the market yesterday."}]'::jsonb, 'b', '"yesterday" needs the past simple, and "go" is irregular: its past form is "went", not the regular "goed". "has went" is wrong because the present perfect uses the past participle "gone", not "went"; "was go" mixes "be" with a base verb.', 1),
  ('bc3de6df-27c5-564f-a509-4feb9efb0100', '1874477b-34e6-5ff5-8fa9-35f4a38c5e2a', 'Complete: "She ___ to the market yesterday."', '[{"id":"a","text":"go"},{"id":"b","text":"went"},{"id":"c","text":"goed"},{"id":"d","text":"goes"}]'::jsonb, 'b', '"yesterday" is a finished past time, so we use the past simple. "go" is irregular: go → went (not the regular "goed"). "go"/"goes" are present simple, which cannot describe yesterday.', 1),
  ('14609924-058c-5c85-b515-6e83bfa1c218', '1874477b-34e6-5ff5-8fa9-35f4a38c5e2a', 'Complete: "Have you ___ eaten couscous?"', '[{"id":"a","text":"yet"},{"id":"b","text":"ago"},{"id":"c","text":"ever"},{"id":"d","text":"yesterday"}]'::jsonb, 'c', '"ever" is placed between the subject and the past participle in present perfect questions to ask about experience at any time in your life: Have you ever eaten couscous? "ago" and "yesterday" mark a finished past time and need the past simple, not the present perfect; "yet" is used in questions but goes at the end (Have you eaten yet?), not in this position.', 2),
  ('63809236-3326-5a22-bf77-ca09b2f1cd0c', '1874477b-34e6-5ff5-8fa9-35f4a38c5e2a', 'Choose the correct negative: "He ___ the test last Monday."', '[{"id":"a","text":"didn''t passed"},{"id":"b","text":"didn''t pass"},{"id":"c","text":"wasn''t pass"},{"id":"d","text":"hasn''t passed"}]'::jsonb, 'b', '"last Monday" is a specific finished time, so we use the past simple, not the present perfect. The negative is "didn''t" + base verb: he didn''t pass. "didn''t passed" double-marks the past; "wasn''t pass" wrongly uses "be"; "hasn''t passed" is present perfect, which cannot go with a specific past time.', 4),
  ('937bbd74-4c72-52a9-a129-ef162fceeeb5', '870d7346-31c1-546f-8e25-ad1a12362ea7', 'Which sentence is correct?', '[{"id":"a","text":"She visited Paris two years ago."},{"id":"b","text":"She has visited Paris two years ago."},{"id":"c","text":"She have visited Paris two years ago."},{"id":"d","text":"She was visited Paris two years ago."}]'::jsonb, 'a', '"two years ago" names a specific finished time, so the past simple is required: she visited Paris. The present perfect (has/have visited) can never be used with a finished-time expression like "ago", which rules out options b and c; "was visited" is a passive form that does not fit here.', 2),
  ('67cf5732-4004-59fe-b4a5-bbc42565a024', '870d7346-31c1-546f-8e25-ad1a12362ea7', 'Complete: "___ the film start when you arrived?"', '[{"id":"a","text":"Did"},{"id":"b","text":"Has"},{"id":"c","text":"Was"},{"id":"d","text":"Were"}]'::jsonb, 'a', 'This asks about a completed event at a specific past moment. Past simple question: Did + subject + base verb. "Did the film start...?"', 3),
  ('7b983cd9-c2c0-5a9c-a73c-ac98bf9d0808', '216cae02-7987-5531-b3fa-6af92e75e33d', 'The phone is ringing and you decide to answer it right now. Which sentence is correct?', '[{"id":"a","text":"I am going to answer it."},{"id":"b","text":"I will answer it."},{"id":"c","text":"I am answering it tomorrow."},{"id":"d","text":"I answer it."}]'::jsonb, 'b', '"Will" is used for a spontaneous decision made at the moment of speaking, so "I will answer it" fits. "am going to" implies a plan made earlier; "am answering it tomorrow" is a future arrangement at the wrong time; "I answer it" (present simple) is not used for a single on-the-spot decision.', 1),
  ('12f16b47-6a4c-5487-99e2-f1f5e592d512', '0ac40b31-da66-5e9a-b82f-2414438a00c5', 'The phone is ringing. Complete: "Don''t worry — I ___ it!"', '[{"id":"a","text":"am going to answer"},{"id":"b","text":"answer"},{"id":"c","text":"will answer"},{"id":"d","text":"am answering"}]'::jsonb, 'c', 'The phone rings and you decide to answer at that very moment, so this is a spontaneous decision: use "will" (I''ll answer it!). "am going to answer" implies a plan made earlier; "answer" (present simple) is for timetables; "am answering" (present continuous) is for fixed arrangements, not an on-the-spot offer.', 1),
  ('4ba459b0-dc9e-57f9-9175-81ba6c0d490d', '0ac40b31-da66-5e9a-b82f-2414438a00c5', 'Look at those black clouds! Complete: "It ___ rain."', '[{"id":"a","text":"will"},{"id":"b","text":"is"},{"id":"c","text":"rains"},{"id":"d","text":"is going to"}]'::jsonb, 'd', 'When you predict the future from evidence you can see right now (black clouds), use "be going to": it is going to rain. "will" is for opinions/predictions without present evidence; "is" alone and "rains" (present simple) do not express this kind of prediction.', 2),
  ('f82a2c0b-e513-5770-8b2a-024116d6b3a1', '0ac40b31-da66-5e9a-b82f-2414438a00c5', 'Choose the correct sentence about a plan already decided:', '[{"id":"a","text":"We will visit Djerba next summer."},{"id":"b","text":"We visit Djerba next summer."},{"id":"c","text":"We visited Djerba next summer."},{"id":"d","text":"We are going to visit Djerba next summer."}]'::jsonb, 'd', 'An intention or plan decided before the moment of speaking uses "be going to": we are going to visit Djerba next summer. "will visit" suits a decision made now or a simple prediction, not a settled plan; "visit" (present simple) needs a timetable; "visited" is past simple and clashes with the future marker "next summer".', 5),
  ('dbf15f17-58e6-5ab5-b012-27b2368c4ca5', 'efb66754-8009-5a3d-995a-6b71e9cf5537', 'A friend is cold. You spontaneously decide to help. Choose the best sentence:', '[{"id":"a","text":"I am going to close the window."},{"id":"b","text":"I close the window."},{"id":"c","text":"I''ll close the window."},{"id":"d","text":"I am closing the window."}]'::jsonb, 'c', 'You decide to help the instant you notice your friend is cold, so this is a spontaneous offer: use "will" (I''ll close the window). "am going to close" implies you had already planned it; "I close" (present simple) and "I am closing" (an action in progress / fixed arrangement) do not express an on-the-spot decision.', 1),
  ('b8ad51f2-0d2f-5a46-ba24-3e956beb4367', 'efb66754-8009-5a3d-995a-6b71e9cf5537', 'Complete: "As soon as she ___, we will start eating."', '[{"id":"a","text":"arrives"},{"id":"b","text":"will arrive"},{"id":"c","text":"is arriving"},{"id":"d","text":"arrived"}]'::jsonb, 'a', 'After time conjunctions like "as soon as", "when", "before" and "until", a future sentence uses the present simple, not "will": as soon as she arrives. So "will arrive" is the classic trap; "is arriving" and "arrived" do not fit the future time-clause rule either.', 2),
  ('e7a6d78a-35e1-5568-a53b-3be72295890c', 'efb66754-8009-5a3d-995a-6b71e9cf5537', 'Choose the correct form: "Look at that cyclist — he ___ fall!"', '[{"id":"a","text":"will"},{"id":"b","text":"is going to"},{"id":"c","text":"would"},{"id":"d","text":"falls"}]'::jsonb, 'b', 'You can see the cyclist losing balance right now, so this is a prediction from present evidence: use "be going to" (he is going to fall). "will" is for predictions based on opinion, not visible signs; "would" is conditional/past; "falls" (present simple) does not express an imminent future event.', 3),
  ('fc5f7dad-9d09-5117-ba74-0cdae2c753c4', 'efb66754-8009-5a3d-995a-6b71e9cf5537', 'Complete: "I think robots ___ do most jobs in the future."', '[{"id":"a","text":"will"},{"id":"b","text":"are going to"},{"id":"c","text":"are"},{"id":"d","text":"would"}]'::jsonb, 'a', '"I think" introduces a personal opinion or prediction about the future with no present evidence, which calls for "will": robots will do most jobs. "are going to" needs visible evidence or a settled plan; "are" alone is not a future form here; "would" is conditional, not a plain future prediction.', 4),
  ('3e22eee7-36b9-5f3a-8e0f-5333d3b76fdf', 'd33dfa7f-2d01-5e1c-aac3-8c969ee05d93', 'Complete: "Students ___ wear a uniform at school. It is the rule."', '[{"id":"a","text":"have to"},{"id":"b","text":"should"},{"id":"c","text":"might"},{"id":"d","text":"could"}]'::jsonb, 'a', '"It is the rule" shows an obligation imposed from outside, which "have to" expresses: students have to wear a uniform. "should" is only advice (weaker than a rule); "might" and "could" express possibility, not obligation.', 3),
  ('013e8407-3e0a-5ecc-af47-acfb7edf86d9', '97d5948a-d69a-595c-a33a-175dd7c3b34e', 'Complete the zero conditional: "If you mix red and blue, you ___ purple."', '[{"id":"a","text":"will get"},{"id":"b","text":"would get"},{"id":"c","text":"got"},{"id":"d","text":"get"}]'::jsonb, 'd', 'Mixing red and blue always gives purple, so this is a general truth = zero conditional, which uses the present simple in both clauses: you get purple. "will get" would make it a first conditional (a specific future result); "would get" is second conditional (imaginary); "got" is past simple and does not fit a timeless fact.', 1),
  ('57545cb8-cc45-5e9a-acc6-42102f111e27', '97d5948a-d69a-595c-a33a-175dd7c3b34e', 'Complete the first conditional: "If she ___ harder, she will pass the baccalaureate."', '[{"id":"a","text":"studied"},{"id":"b","text":"will study"},{"id":"c","text":"studies"},{"id":"d","text":"would study"}]'::jsonb, 'c', 'In the first conditional, the if-clause uses the present simple and "will" appears only in the main clause: if she studies harder, she will pass. So "will study" inside the if-clause is the classic mistake; "studied"/"would study" belong to the second conditional (imaginary), not this realistic situation.', 2),
  ('ee916acc-ccc1-509c-934c-be74d6578dc8', '97d5948a-d69a-595c-a33a-175dd7c3b34e', 'Complete the second conditional: "If I ___ a superhero, I would fly to school."', '[{"id":"a","text":"am"},{"id":"b","text":"will be"},{"id":"c","text":"were"},{"id":"d","text":"would be"}]'::jsonb, 'c', 'Being a superhero is imaginary, so this is a second conditional. In standard English the verb "be" takes "were" for all persons in the if-clause: if I were a superhero. "am" is present (real); "will be" belongs to the first conditional; "would be" is for the main clause, not the if-clause.', 3),
  ('fc64ccc6-a874-5048-aa2b-ec4bf7fedd1b', 'aa6477e9-c60c-5771-9828-15c32bace66c', 'Choose the correct main clause: "If you press this button, the machine ___,"', '[{"id":"a","text":"started"},{"id":"b","text":"starts"},{"id":"c","text":"would start"},{"id":"d","text":"will starting"}]'::jsonb, 'b', 'Pressing the button always makes the machine start, so this is a zero conditional (a reliable fact): both clauses use the present simple, hence "the machine starts". "started" is past simple; "would start" is second conditional (imaginary); "will starting" is not a valid verb form.', 1),
  ('349da296-708e-512c-98a5-f79c0d32d5fd', 'aa6477e9-c60c-5771-9828-15c32bace66c', 'Complete: "If I ___ you, I would talk to the teacher about this problem."', '[{"id":"a","text":"am"},{"id":"b","text":"was"},{"id":"c","text":"were"},{"id":"d","text":"would be"}]'::jsonb, 'c', '"If I were you" gives advice about an imaginary situation, so it is a second conditional. In standard English, "be" takes "were" for every person in the if-clause: If I were you. "am" is the real present; "was" is the common informal form but not the exam-standard one; "would be" belongs in the main clause, not the if-clause.', 2),
  ('dd9dffa7-3d7a-5ecc-a39f-486149eb142f', 'aa6477e9-c60c-5771-9828-15c32bace66c', 'Which sentence is a correct first conditional?', '[{"id":"a","text":"If it will rain, we stay inside."},{"id":"b","text":"If it rained, we will stay inside."},{"id":"c","text":"If it rains, we would stay inside."},{"id":"d","text":"If it rains, we will stay inside."}]'::jsonb, 'd', 'First conditional: if + present simple (rains) + will + base verb (will stay), as in option d. Option a wrongly puts "will" in the if-clause; option b mixes past simple ("rained") with "will"; option c uses "would" in the main clause, which belongs to the second conditional.', 3),
  ('cf42ec20-80b2-537e-a00e-3c58063c62ff', '69ebe656-2d06-5124-80fc-9f898ee0a2b8', 'Choose the correct passive form: "The windows ___ every week." (present simple passive)', '[{"id":"a","text":"clean"},{"id":"b","text":"are cleaned"},{"id":"c","text":"is cleaned"},{"id":"d","text":"were cleaned"}]'::jsonb, 'b', 'The passive = "be" + past participle. "The windows" is plural and the time is present (every week), so we use ARE + cleaned: the windows are cleaned. "clean" is active; "is cleaned" wrongly uses the singular "is"; "were cleaned" is past, not present.', 1),
  ('0b38e0c4-8ce6-5c7a-a51b-cd1d96b9c7b9', '69ebe656-2d06-5124-80fc-9f898ee0a2b8', 'Complete: "Arabic ___ in Tunisia." (present simple passive of ''speak'')', '[{"id":"a","text":"speaks"},{"id":"b","text":"is spoken"},{"id":"c","text":"are spoken"},{"id":"d","text":"was spoken"}]'::jsonb, 'b', '"Arabic" (a language) is singular, so the present simple passive uses IS + the past participle "spoken": Arabic is spoken in Tunisia. "speaks" is active; "are spoken" wrongly uses the plural "are"; "was spoken" is past, not present.', 2),
  ('1886b0c7-fccb-565d-92ff-f84e3a6993f4', '69ebe656-2d06-5124-80fc-9f898ee0a2b8', 'Turn this active sentence into passive: "Someone broke the vase." The correct passive is:', '[{"id":"a","text":"The vase is broken."},{"id":"b","text":"The vase was broken."},{"id":"c","text":"The vase were broken."},{"id":"d","text":"The vase was break."}]'::jsonb, 'b', 'The active verb "broke" is past simple, so the passive keeps the past tense: "the vase" (singular) + WAS + past participle "broken". "is broken" changes the tense to present; "were broken" wrongly uses the plural "were"; "was break" uses the base verb instead of the past participle.', 3),
  ('a9e2968b-a92d-5746-9362-164238da0854', '69ebe656-2d06-5124-80fc-9f898ee0a2b8', 'Complete: "The exam ___ yesterday by all the students." (past simple passive of ''take'')', '[{"id":"a","text":"is taken"},{"id":"b","text":"are taken"},{"id":"c","text":"was taken"},{"id":"d","text":"took"}]'::jsonb, 'c', '"yesterday" signals past tense and "the exam" is singular, so the past simple passive is WAS + the past participle "taken": the exam was taken. "is taken"/"are taken" are present; "took" is the active past, not the passive.', 5),
  ('43b02806-bc22-570c-b797-0b37b895db64', '50566438-5c32-582c-9b59-43a0b96cc9a4', 'Transform to passive: "They make these shoes in Italy." The correct passive is:', '[{"id":"a","text":"These shoes are made in Italy."},{"id":"b","text":"These shoes were made in Italy."},{"id":"c","text":"These shoes is made in Italy."},{"id":"d","text":"These shoes are make in Italy."}]'::jsonb, 'a', 'The active verb "make" is present simple, so the passive stays present. "These shoes" is plural → ARE + the past participle "made": these shoes are made in Italy. "were made" changes the tense to past; "is made" wrongly uses the singular "is"; "are make" keeps the base verb instead of the participle.', 1),
  ('8fdfff8c-ddbd-5448-85e5-83a9f52730c9', '50566438-5c32-582c-9b59-43a0b96cc9a4', 'Transform to passive: "The teacher corrected our homework." The correct passive is:', '[{"id":"a","text":"Our homework is corrected by the teacher."},{"id":"b","text":"Our homework were corrected by the teacher."},{"id":"c","text":"Our homework was correct by the teacher."},{"id":"d","text":"Our homework was corrected by the teacher."}]'::jsonb, 'd', 'The active verb "corrected" is past simple, and "our homework" is singular (uncountable), so the passive is WAS + the past participle "corrected": our homework was corrected by the teacher. "is corrected" changes the tense; "were corrected" wrongly uses the plural "were"; "was correct" uses the adjective/base form, not the past participle.', 2),
  ('c961b0e5-2864-5565-abe0-a6579f21445f', '50566438-5c32-582c-9b59-43a0b96cc9a4', 'Choose the sentence where the passive is used correctly:', '[{"id":"a","text":"The pyramids were build thousands of years ago."},{"id":"b","text":"The pyramids were built thousands of years ago."},{"id":"c","text":"The pyramids was built thousands of years ago."},{"id":"d","text":"The pyramids are built thousands of years ago."}]'::jsonb, 'b', '"The pyramids" is plural and "thousands of years ago" is past, so we use WERE + the past participle "built": the pyramids were built. "were build" keeps the base verb instead of the participle; "was built" wrongly uses the singular "was"; "are built" is present and clashes with the past time marker.', 3),
  ('86e69d95-8ade-5dc8-bc07-e6ac553e4be0', '50566438-5c32-582c-9b59-43a0b96cc9a4', 'Active: "A student finds a wallet." → Passive:', '[{"id":"a","text":"A wallet is found by a student."},{"id":"b","text":"A wallet found by a student."},{"id":"c","text":"A wallet were found by a student."},{"id":"d","text":"A wallet was found by a student."}]'::jsonb, 'a', 'The active verb "finds" is present simple, and "a wallet" is singular, so the passive is IS + the past participle "found": a wallet is found by a student. Option b drops the auxiliary "is"; "were found" wrongly uses the plural past "were"; "was found" changes the tense to past.', 4),
  ('01868ac1-1c85-531f-b957-c922c262d7c3', '50566438-5c32-582c-9b59-43a0b96cc9a4', 'Complete the sentence with the correct passive: "The new library ___ last year." (open)', '[{"id":"a","text":"is opened"},{"id":"b","text":"was opened"},{"id":"c","text":"opened"},{"id":"d","text":"were opened"}]'::jsonb, 'b', '"last year" signals past tense and "the new library" is singular, so the passive is WAS + the past participle "opened": the new library was opened last year. "is opened" is present; "opened" alone is the active past, not the passive; "were opened" wrongly uses the plural "were".', 6),
  ('c76b8b99-9da2-5728-9cb2-f075223db346', 'f34bbeba-a514-5828-9e27-2a8b3711fb93', 'What is the comparative form of the adjective "happy"?', '[{"id":"a","text":"more happy than"},{"id":"b","text":"happier than"},{"id":"c","text":"happyer than"},{"id":"d","text":"the happiest"}]'::jsonb, 'b', 'Short adjectives ending in consonant + -y change the y to i and add -er: happy → happier (than). "more happy" is wrong because "more" is only for long adjectives; "happyer" keeps the y instead of changing it to i; "the happiest" is the superlative, not the comparative.', 2),
  ('4ae0793a-71f0-59d6-9e51-a31b37912048', 'f9d67f42-c6fd-52d1-b4d8-658c24c4069e', 'Choose the correct relative pronoun: "The student ___ won the prize is in my class."', '[{"id":"a","text":"which"},{"id":"b","text":"whose"},{"id":"c","text":"where"},{"id":"d","text":"who"}]'::jsonb, 'd', 'We use "who" for people, and "the student" is a person: the student who won the prize. "which" is for things; "where" is for places; "whose" shows possession (the student''s...), which is not the meaning here.', 1),
  ('a387198b-d83b-52a6-9faf-fd4740453fb6', 'f9d67f42-c6fd-52d1-b4d8-658c24c4069e', 'Choose the correct comparative: "A cheetah is ___ a lion."', '[{"id":"a","text":"more fast than"},{"id":"b","text":"fastest than"},{"id":"c","text":"as fast than"},{"id":"d","text":"faster than"}]'::jsonb, 'd', '"fast" is a short (one-syllable) adjective, so the comparative adds -er + than: faster than. "more fast" is wrong because "more" is only for long adjectives; "fastest than" is a superlative form (and superlatives never take "than"); "as fast than" mixes the "as...as" pattern with "than".', 3),
  ('53788e4f-8c7e-5bbf-86e1-f3ffc3ebb034', 'f9d67f42-c6fd-52d1-b4d8-658c24c4069e', 'Complete: "Mount Everest is ___ mountain in the world."', '[{"id":"a","text":"more high"},{"id":"b","text":"the most high"},{"id":"c","text":"higher"},{"id":"d","text":"the highest"}]'::jsonb, 'd', 'Comparing one mountain to all others needs a superlative. "high" is a short adjective, so the superlative adds -est and requires "the": the highest. "the most high" is wrong because "most" is only for long adjectives; "more high" and "higher" are comparatives (for two things), not superlatives.', 4),
  ('684457b0-f151-5355-b7de-b1cc7331c8e0', '2cbeb6e5-2960-512e-9f42-e5cbe625a305', 'Choose the correct relative pronoun: "The scientist ___ research won the Nobel Prize gave a lecture."', '[{"id":"a","text":"who"},{"id":"b","text":"which"},{"id":"c","text":"whose"},{"id":"d","text":"that"}]'::jsonb, 'c', 'The research belongs to the scientist, so we need the possessive relative pronoun "whose": the scientist whose research won the Nobel Prize (= the scientist''s research). "who" replaces a person as subject/object, not a possessor; "which"/"that" refer to things and cannot show possession here.', 1)
) AS v(id, exercise_id, prompt, options, correct_option, explanation, display_order)
WHERE EXISTS (SELECT 1 FROM public.exercises e WHERE e.id = v.exercise_id::uuid)
ON CONFLICT (id) DO UPDATE SET
  exercise_id = EXCLUDED.exercise_id,
  prompt = EXCLUDED.prompt,
  options = EXCLUDED.options,
  correct_option = EXCLUDED.correct_option,
  explanation = EXCLUDED.explanation,
  display_order = EXCLUDED.display_order;
