-- ---------------------------------------------------------------------------
-- CLIENT_ERRORS — la boîte noire du refus d'authentification.
--
-- POURQUOI ELLE EXISTE. Le bug « Invalid token » en fin d'exercice n'a JAMAIS
-- livré son message exact : au moment où il se produit, le jeton de l'élève est
-- cassé, donc rien de ce qui exige une authentification ne peut le raconter. Le
-- correctif de #914 repose sur une hypothèse — l'horloge de l'appareil ment de
-- plus de 90 s — que rien n'a encore mesurée. Cette table sert à la départager
-- de ses deux rivales, chiffres en main :
--
--   * ttl_s <= 0        → expiration classique, le jeton était bel et bien mort ;
--   * ttl_s > 60        → jeton VALIDE côté client et pourtant refusé : c'est la
--                         dérive d'horloge (ou un refus côté serveur) ;
--   * last_hidden_ms    → l'onglet revenait de veille, cas mobile.
--     > 60000
--
-- CE QU'ELLE NE CONTIENT PAS. Aucun identifiant d'utilisateur, par construction :
-- la route qui écrit ici n'exige aucun jeton (elle ne pourrait pas — voir
-- ci-dessus) et n'en dérive donc aucune identité. `client_id` est la clé de file
-- d'une soumission, pas une personne. C'est aussi ce qui rend la table sûre :
-- personne ne peut y écrire au nom de quelqu'un d'autre, puisqu'elle ne
-- prétend nommer personne. (INPDP / mineurs — même politique que
-- `monitoring.ts`, qui ne transmet aucune PII.)
--
-- ACCÈS. RLS ACTIVÉE ET AUCUNE POLICY : c'est l'expression la plus stricte du
-- modèle — tout est refusé, sauf la service role key, qui contourne RLS par
-- définition. Les REVOKE explicites doublent la garde au niveau des privilèges,
-- parce qu'une policy ajoutée par erreur plus tard ouvrirait la table sans eux.
-- Précédent maison : `rate_limit_events` et `subject_leaderboard_totals` sont
-- déjà « client-invisibles » (voir 20260612221000_baseline_table_grants.sql, qui
-- pose la règle : toute CREATE TABLE embarque ses propres GRANT).
-- ---------------------------------------------------------------------------
-- REQUÊTE DE DIAGNOSTIC — laquelle des trois hypothèses gagne ?
--
--   SELECT date_trunc('hour', created_at)                              AS heure,
--          count(*)                                                     AS erreurs,
--          count(*) FILTER (WHERE ttl_s <= 0)                           AS jeton_expire,
--          count(*) FILTER (WHERE ttl_s > 60)                           AS jeton_valide_refuse,
--          count(*) FILTER (WHERE last_hidden_ms > 60000)               AS retour_de_veille,
--          round(avg(ttl_s))                                            AS ttl_moyen_s
--     FROM public.client_errors
--    WHERE created_at > now() - interval '7 days'
--    GROUP BY 1
--    ORDER BY 1 DESC;
--
-- Lecture : une colonne `jeton_valide_refuse` non nulle DISQUALIFIE l'expiration
-- simple et confirme le diagnostic d'horloge de #914. Une colonne
-- `retour_de_veille` dominante désignerait plutôt le gel des minuteries mobiles.
-- Les deux peuvent coexister — ce sont deux fenêtres du même trou.
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.client_errors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Où, dans le parcours, l'échec s'est produit ('submit', 'outbox-flush', …).
  stage TEXT NOT NULL,
  -- La clé de file de la soumission concernée. Rattache l'erreur à un travail,
  -- jamais à une personne.
  client_id TEXT,
  -- Le statut HTTP quand on a pu le lire. Souvent NULL : une server fn TanStack
  -- ne rend au client qu'un message, pas un statut.
  http_status INT,
  err_message TEXT,
  -- Secondes restant au jeton au moment du refus, d'après `expires_at` et
  -- l'horloge de l'appareil. NÉGATIF = l'appareil se savait expiré.
  ttl_s INT,
  -- Temps cumulé passé onglet caché depuis le chargement, et durée de la
  -- DERNIÈRE veille. Les deux, parce qu'une longue veille unique et un
  -- va-et-vient permanent ne racontent pas la même panne.
  hidden_total_ms BIGINT,
  last_hidden_ms BIGINT,
  user_agent TEXT,
  payload JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

-- Le seul axe de lecture prévu est temporel (voir la requête ci-dessus).
CREATE INDEX IF NOT EXISTS idx_client_errors_created
  ON public.client_errors(created_at DESC);

ALTER TABLE public.client_errors ENABLE ROW LEVEL SECURITY;

-- Aucune policy, et les privilèges retirés par-dessus : seule la service role
-- key écrit ou lit ici.
REVOKE ALL ON public.client_errors FROM PUBLIC, anon, authenticated;
