-- Server-authoritative dungeon runs (anti-cheat):
-- - no correct answers exposed by question fetch
-- - answers validated server-side in order
-- - rewards computed from persisted run state, not client payload

CREATE TABLE IF NOT EXISTS public.dungeon_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  current_floor INT NOT NULL DEFAULT 1 CHECK (current_floor >= 1),
  floors_cleared INT NOT NULL DEFAULT 0 CHECK (floors_cleared >= 0),
  total_correct INT NOT NULL DEFAULT 0 CHECK (total_correct >= 0),
  total_answered INT NOT NULL DEFAULT 0 CHECK (total_answered >= 0),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'failed', 'completed')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  ended_at TIMESTAMPTZ,
  duration_seconds INT,
  rewarded_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp()
);

CREATE TABLE IF NOT EXISTS public.dungeon_run_questions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id UUID NOT NULL REFERENCES public.dungeon_runs(id) ON DELETE CASCADE,
  question_id UUID NOT NULL REFERENCES public.questions(id) ON DELETE RESTRICT,
  assigned_floor INT NOT NULL CHECK (assigned_floor >= 1),
  answered_at TIMESTAMPTZ,
  selected_choice TEXT,
  is_correct BOOLEAN,
  created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  UNIQUE (run_id, question_id),
  UNIQUE (run_id, assigned_floor)
);

ALTER TABLE public.dungeon_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dungeon_run_questions ENABLE ROW LEVEL SECURITY;

CREATE INDEX IF NOT EXISTS idx_dungeon_runs_user_created
  ON public.dungeon_runs(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_dungeon_run_questions_run_floor
  ON public.dungeon_run_questions(run_id, assigned_floor);

CREATE OR REPLACE FUNCTION public.start_dungeon_run()
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user UUID := auth.uid();
  v_run_id UUID;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  INSERT INTO public.dungeon_runs (user_id)
  VALUES (v_user)
  RETURNING id INTO v_run_id;

  RETURN v_run_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_dungeon_questions(
  p_run_id UUID,
  p_batch_size INT DEFAULT 5
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user UUID := auth.uid();
  v_run public.dungeon_runs;
  v_max_difficulty INT;
  v_questions JSONB := '[]'::jsonb;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  IF p_run_id IS NULL THEN
    RAISE EXCEPTION 'Run id is required';
  END IF;

  IF p_batch_size IS NULL OR p_batch_size < 1 OR p_batch_size > 20 THEN
    RAISE EXCEPTION 'Invalid batch size';
  END IF;

  SELECT *
  INTO v_run
  FROM public.dungeon_runs
  WHERE id = p_run_id
    AND user_id = v_user
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid dungeon run.';
  END IF;

  IF v_run.status <> 'active' THEN
    RAISE EXCEPTION 'Dungeon run is not active.';
  END IF;

  v_max_difficulty := LEAST(3, CEIL(v_run.current_floor::NUMERIC / 5.0)::INT);

  WITH inserted AS (
    INSERT INTO public.dungeon_run_questions (run_id, question_id, assigned_floor)
    SELECT p_run_id, c.id, v_run.current_floor + row_number() OVER (ORDER BY c.id) - 1
    FROM (
      SELECT q.id
      FROM public.questions q
      JOIN public.exercises e ON e.id = q.exercise_id
      WHERE e.difficulty <= v_max_difficulty
        AND NOT EXISTS (
          SELECT 1
          FROM public.dungeon_run_questions rq
          WHERE rq.run_id = p_run_id
            AND rq.question_id = q.id
        )
      ORDER BY random()
      LIMIT p_batch_size
    ) c
    ON CONFLICT DO NOTHING
    RETURNING question_id, assigned_floor
  )
  SELECT COALESCE(jsonb_agg(
    jsonb_build_object(
      'id', q.id,
      'prompt', q.prompt,
      'options', q.options,
      'explanation', q.explanation,
      'assignedFloor', ins.assigned_floor,
      'exercises', jsonb_build_object(
        'difficulty', e.difficulty,
        'subject_id', s.id,
        'subjects', jsonb_build_object(
          'name_fr', s.name_fr,
          'color_token', s.color_token,
          'icon', s.icon
        )
      )
    )
    ORDER BY ins.assigned_floor
  ), '[]'::jsonb)
  INTO v_questions
  FROM inserted ins
  JOIN public.questions q ON q.id = ins.question_id
  JOIN public.exercises e ON e.id = q.exercise_id
  JOIN public.subjects s ON s.id = e.subject_id;

  RETURN jsonb_build_object(
    'currentFloor', v_run.current_floor,
    'questions', v_questions
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.submit_dungeon_answer(
  p_run_id UUID,
  p_question_id UUID,
  p_choice TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user UUID := auth.uid();
  v_run public.dungeon_runs;
  v_run_question public.dungeon_run_questions;
  v_question public.questions;
  v_is_correct BOOLEAN;
  v_next_floor INT;
  v_floors_cleared INT;
  v_total_correct INT;
  v_total_answered INT;
  v_status TEXT;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  IF p_run_id IS NULL OR p_question_id IS NULL THEN
    RAISE EXCEPTION 'Run and question are required';
  END IF;

  IF p_choice IS NULL OR btrim(p_choice) = '' THEN
    RAISE EXCEPTION 'Choice is required';
  END IF;

  SELECT *
  INTO v_run
  FROM public.dungeon_runs
  WHERE id = p_run_id
    AND user_id = v_user
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid dungeon run.';
  END IF;

  IF v_run.status <> 'active' THEN
    RAISE EXCEPTION 'Dungeon run is not active.';
  END IF;

  SELECT *
  INTO v_run_question
  FROM public.dungeon_run_questions
  WHERE run_id = p_run_id
    AND question_id = p_question_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Question is not assigned to this run.';
  END IF;

  IF v_run_question.answered_at IS NOT NULL THEN
    RAISE EXCEPTION 'This dungeon question is already answered.';
  END IF;

  IF v_run_question.assigned_floor <> v_run.current_floor THEN
    RAISE EXCEPTION 'Invalid floor progression.';
  END IF;

  SELECT *
  INTO v_question
  FROM public.questions
  WHERE id = p_question_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Question not found.';
  END IF;

  v_is_correct := (v_question.correct_option = p_choice);

  UPDATE public.dungeon_run_questions
  SET answered_at = clock_timestamp(),
      selected_choice = p_choice,
      is_correct = v_is_correct
  WHERE id = v_run_question.id;

  IF v_is_correct THEN
    v_next_floor := v_run.current_floor + 1;
    v_floors_cleared := v_run.floors_cleared + 1;
    v_total_correct := v_run.total_correct + 1;
    v_total_answered := v_run.total_answered + 1;
    v_status := 'active';

    UPDATE public.dungeon_runs
    SET current_floor = v_next_floor,
        floors_cleared = v_floors_cleared,
        total_correct = v_total_correct,
        total_answered = v_total_answered
    WHERE id = p_run_id;
  ELSE
    v_next_floor := v_run.current_floor;
    v_floors_cleared := v_run.floors_cleared;
    v_total_correct := v_run.total_correct;
    v_total_answered := v_run.total_answered + 1;
    v_status := 'failed';

    UPDATE public.dungeon_runs
    SET status = 'failed',
        ended_at = clock_timestamp(),
        total_answered = v_total_answered
    WHERE id = p_run_id;
  END IF;

  RETURN jsonb_build_object(
    'isCorrect', v_is_correct,
    'nextFloor', v_next_floor,
    'floorsCleared', v_floors_cleared,
    'totalCorrect', v_total_correct,
    'totalAnswered', v_total_answered,
    'runStatus', v_status,
    'questionId', v_question.id,
    'prompt', v_question.prompt,
    'correctChoice', v_question.correct_option,
    'explanation', v_question.explanation
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.finalize_dungeon_run(
  p_run_id UUID,
  p_duration_seconds INT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user UUID := auth.uid();
  v_run public.dungeon_runs;
  v_xp_earned INT;
  v_coins_earned INT;
  v_final_status TEXT;
BEGIN
  IF v_user IS NULL THEN
    RAISE EXCEPTION 'Unauthorized';
  END IF;

  IF p_run_id IS NULL THEN
    RAISE EXCEPTION 'Run id is required';
  END IF;

  IF p_duration_seconds IS NULL OR p_duration_seconds < 0 OR p_duration_seconds > 86400 THEN
    RAISE EXCEPTION 'Invalid run duration';
  END IF;

  SELECT *
  INTO v_run
  FROM public.dungeon_runs
  WHERE id = p_run_id
    AND user_id = v_user
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Invalid dungeon run.';
  END IF;

  v_xp_earned := v_run.floors_cleared * 15;
  v_coins_earned := (v_run.floors_cleared / 5) * 5;

  IF v_run.rewarded_at IS NULL THEN
    IF v_xp_earned > 0 THEN
      PERFORM public.award_xp(v_user, v_xp_earned);
    END IF;

    IF v_coins_earned > 0 THEN
      PERFORM public.award_coins(v_user, v_coins_earned);
    END IF;

    v_final_status := CASE WHEN v_run.status = 'active' THEN 'completed' ELSE v_run.status END;

    UPDATE public.dungeon_runs
    SET status = v_final_status,
        ended_at = COALESCE(v_run.ended_at, clock_timestamp()),
        duration_seconds = p_duration_seconds,
        rewarded_at = clock_timestamp()
    WHERE id = p_run_id;
  ELSE
    v_final_status := v_run.status;
  END IF;

  RETURN jsonb_build_object(
    'floorsCleared', v_run.floors_cleared,
    'totalCorrect', v_run.total_correct,
    'totalAnswered', v_run.total_answered,
    'xpEarned', v_xp_earned,
    'coinsEarned', v_coins_earned,
    'durationSeconds', p_duration_seconds,
    'status', v_final_status
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.start_dungeon_run() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_dungeon_questions(uuid, int) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.submit_dungeon_answer(uuid, uuid, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.finalize_dungeon_run(uuid, int) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.start_dungeon_run() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_dungeon_questions(uuid, int) TO authenticated;
GRANT EXECUTE ON FUNCTION public.submit_dungeon_answer(uuid, uuid, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.finalize_dungeon_run(uuid, int) TO authenticated;
